// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:46:33
// Description   : vStockReturnEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vStockReturnEntityTypeConfig : IEntityTypeConfiguration<vStockReturn>, IEdmEntityConfiguration<vStockReturn>
    {

        #region Implements IEntityTypeConfiguration<vStockReturn>
        
        public void Configure(EntityTypeBuilder<vStockReturn> builder) { InternalConfigure(builder); }

        #endregion
        
        #region Implements IEdmEntityConfiguration<vStockReturn>

        public string EntitySetName { get; } = "vStockReturns";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vStockReturn> builder) { InternalConfigureEdmEntity(builder); }

        #endregion
        
        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vStockReturn
        {
            builder.ToTable("vStockReturn");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.DocumentID });
        }
        
        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vStockReturn
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.DocumentID });
        }

        #endregion

    }

}
