// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:46:03
// Description   : vInvoiceOpnameDetailsEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vInvoiceOpnameDetailsEntityTypeConfig : IEntityTypeConfiguration<vInvoiceOpnameDetails>, IEdmEntityConfiguration<vInvoiceOpnameDetails>
    {

        #region Implements IEntityTypeConfiguration<vInvoiceOpnameDetails>
        
        public void Configure(EntityTypeBuilder<vInvoiceOpnameDetails> builder) { InternalConfigure(builder); }

        #endregion
        
        #region Implements IEdmEntityConfiguration<vInvoiceOpnameDetails>

        public string EntitySetName { get; } = "vInvoiceOpnameDetails";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vInvoiceOpnameDetails> builder) { InternalConfigureEdmEntity(builder); }

        #endregion
        
        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vInvoiceOpnameDetails
        {
            builder.ToTable("vInvoiceOpnameDetails");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.DocumentID, p.InvoiceDocumentID });
        }
        
        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vInvoiceOpnameDetails
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.DocumentID, p.InvoiceDocumentID });
        }

        #endregion

    }

}
