// ===================================================================================
// Author        : System
// Created date  : 30 Aug 2020 07:11:01
// Description   : mvCustomerTableProvider partial class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Wismapi.Data.Entity;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Linq.Expressions;

namespace AIO.IDOS3.Data.Entity
{

    public partial class mvCustomerHistoricalTableProvider : DataTableProvider<mvCustomerHistorical>
    {

        #region Methods

        protected override async Task OnBeginInsertDataAsync(BeginOperationDataEventArgs<CustomerHistorical> e)
        {
            e.Data.CreatedDate = await DbContext.GetDatabaseUtcDateTimeAsync();

            await base.OnBeginInsertDataAsync(e);
        }

        protected override async Task OnBeginUpdateDataAsync(BeginOperationDataEventArgs<CustomerHistorical> e)
        {

            await base.OnBeginUpdateDataAsync(e);
        }

        protected override async Task OnBeginDeleteDataAsync(BeginOperationDataEventArgs<CustomerHistorical> e)
        {


            await base.OnBeginDeleteDataAsync(e);
        }

        #endregion

    }

}
