// ===================================================================================
// Author        : System
// Created date  : 08 Oct 2020 05:23:04
// Description   : mvPaymentCollectionDetailsEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using AIO.IDOS3.Data.Entity;
using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Mobile.Data.Entity
{

    public class mvPaymentCollectionDetailsEntityTypeConfig : IEntityTypeConfiguration<mvPaymentCollectionDetails>, IEdmEntityConfiguration<mvPaymentCollectionDetails>
    {

        #region Fields

        private vPaymentCollectionDetailsEntityTypeConfig parentConfig = new vPaymentCollectionDetailsEntityTypeConfig();

        #endregion

        #region Implements IEntityTypeConfiguration<mvPaymentCollectionDetails>

        public void Configure(EntityTypeBuilder<mvPaymentCollectionDetails> builder)
        {
            parentConfig.InternalConfigure(builder);

            builder.HasOne(p => p.Parent)
                .WithMany(q => q.ChildDetails)
                .HasForeignKey(p => new { p.DocumentID })
                .OnDelete(DeleteBehavior.Cascade);
        }

        #endregion

        #region Implements IEdmEntityConfiguration<mvPaymentCollectionDetails>

        public string EntitySetName { get { return parentConfig.EntitySetName; } }

        public void ConfigureEdmEntity(EntityTypeConfiguration<mvPaymentCollectionDetails> builder) { parentConfig.InternalConfigureEdmEntity(builder); }

        #endregion

    }

}
