// ===================================================================================
// Author        : System
// Created date  : 24 Sep 2020 04:37:06
// Description   : vSalesPromotionProductEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vSalesPromotionProductEntityTypeConfig : IEntityTypeConfiguration<vSalesPromotionProduct>, IEdmEntityConfiguration<vSalesPromotionProduct>
    {

        #region Implements IEntityTypeConfiguration<vSalesPromotionProduct>

        public void Configure(EntityTypeBuilder<vSalesPromotionProduct> builder) { InternalConfigure(builder); }

        #endregion

        #region Implements IEdmEntityConfiguration<vSalesPromotionProduct>

        public string EntitySetName { get; } = "vSalesPromotionProducts";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vSalesPromotionProduct> builder) { InternalConfigureEdmEntity(builder); }

        #endregion

        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vSalesPromotionProduct
        {
            builder.ToTable("vSalesPromotionProduct");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.SalesPromotionID, p.ProductID });
        }

        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vSalesPromotionProduct
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.SalesPromotionID, p.ProductID });
        }

        #endregion

    }

}
