// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:46:07
// Description   : vPaymentReconciliationMainEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vPaymentReconciliationMainEntityTypeConfig : IEntityTypeConfiguration<vPaymentReconciliationMain>, IEdmEntityConfiguration<vPaymentReconciliationMain>
    {

        #region Implements IEntityTypeConfiguration<vPaymentReconciliationMain>
        
        public void Configure(EntityTypeBuilder<vPaymentReconciliationMain> builder) { InternalConfigure(builder); }

        #endregion
        
        #region Implements IEdmEntityConfiguration<vPaymentReconciliationMain>

        public string EntitySetName { get; } = "vPaymentReconciliationMains";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vPaymentReconciliationMain> builder) { InternalConfigureEdmEntity(builder); }

        #endregion
        
        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vPaymentReconciliationMain
        {
            builder.ToTable("vPaymentReconciliationMain");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.DocumentID });
        }
        
        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vPaymentReconciliationMain
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.DocumentID });
        }

        #endregion

    }

}
