// ===================================================================================
// Author        : System
// Created date  : 23 Nov 2020 03:27:38
// Description   : mvUserEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Wismapi.Data.SQLiteNet;

namespace AIO.IDOS3.Mobile.Data.SQLiteNet
{

    public class mvUserEntityTypeConfig : IEdmEntityConfiguration<mvUser>
    {

        #region Implements IEdmEntityConfiguration<mvUser>

        public string EntitySetName { get; } = "vUsers";

        #endregion

    }

}
