// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:45:09
// Description   : PermissionObjectEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AIO.IDOS3.Data.Entity
{

    public class PermissionObjectEntityTypeConfig : IEntityTypeConfiguration<PermissionObject>
    {

        #region Implements IEntityTypeConfiguration<PermissionObject>
        
        public void Configure(EntityTypeBuilder<PermissionObject> builder) { InternalConfigure(builder); }

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : PermissionObject
        {
            builder.ToTable("PermissionObject");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.ID });
        }
        
        #endregion

    }

}
