// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:46:16
// Description   : vSalesOrderSampleSummaryEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vSalesOrderSampleSummaryEntityTypeConfig : IEntityTypeConfiguration<vSalesOrderSampleSummary>, IEdmEntityConfiguration<vSalesOrderSampleSummary>
    {

        #region Implements IEntityTypeConfiguration<vSalesOrderSampleSummary>

        public void Configure(EntityTypeBuilder<vSalesOrderSampleSummary> builder)
        {
            InternalConfigure(builder);

            builder.HasOne(p => p.Parent)
                .WithMany(q => q.ChildSummaries)
                .HasForeignKey(p => p.DocumentID)
                .OnDelete(DeleteBehavior.Cascade);
        }

        #endregion

        #region Implements IEdmEntityConfiguration<vSalesOrderSampleSummary>

        public string EntitySetName { get; } = "vSalesOrderSampleSummaries";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vSalesOrderSampleSummary> builder) { InternalConfigureEdmEntity(builder); }

        #endregion

        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vSalesOrderSampleSummary
        {
            builder.ToTable("vSalesOrderSampleSummary");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.DocumentID, p.ProductID });
        }

        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vSalesOrderSampleSummary
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.DocumentID, p.ProductID });
        }

        #endregion

    }

}
