// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:46:08
// Description   : vProductLotEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vProductLotEntityTypeConfig : IEntityTypeConfiguration<vProductLot>, IEdmEntityConfiguration<vProductLot>
    {

        #region Implements IEntityTypeConfiguration<vProductLot>

        public void Configure(EntityTypeBuilder<vProductLot> builder)
        {
            InternalConfigure(builder);

            builder.HasOne(p => p.ExtendStockOnHandCurrent)
                .WithOne(q => q.ExtendProductLot)
                .HasForeignKey<vStockOnHandCurrent>(q => q.ProductLotID);
        }

        #endregion

        #region Implements IEdmEntityConfiguration<vProductLot>

        public string EntitySetName { get; } = "vProductLots";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vProductLot> builder) { InternalConfigureEdmEntity(builder); }

        #endregion

        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vProductLot
        {
            builder.ToTable("vProductLot");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.ID });
        }

        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vProductLot
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.ID });
        }

        #endregion

    }

}
