// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:46:09
// Description   : vRoleEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vRoleEntityTypeConfig : IEntityTypeConfiguration<vRole>, IEdmEntityConfiguration<vRole>
    {

        #region Implements IEntityTypeConfiguration<vRole>
        
        public void Configure(EntityTypeBuilder<vRole> builder) { InternalConfigure(builder); }

        #endregion
        
        #region Implements IEdmEntityConfiguration<vRole>

        public string EntitySetName { get; } = "vRoles";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vRole> builder) { InternalConfigureEdmEntity(builder); }

        #endregion
        
        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vRole
        {
            builder.ToTable("vRole");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.ID });
        }
        
        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vRole
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.ID });
        }

        #endregion

    }

}
