// ===================================================================================
// Author        : System
// Created date  : 30 Aug 2020 07:11:04
// Description   : mvSalesOrderSwapSyncProvider partial class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Mobile.Data.Entity
{

    public partial class mvSalesOrderSwapSyncProvider : DataSyncProvider<mvSalesOrderSwap>
    {

        #region Fields

        public static string Selector = "DocumentID,DocumentCode,TransactionDate,SalesmanID,SalesmanCode,SalesmanName,Salesman,WarehouseID,WarehouseCode,WarehouseName,Warehouse,SiteID,AreaID,RegionID,TerritoryID,CompanyID,CustomerID,CustomerCode,CustomerName,Customer,ReferenceNumber,DODocumentID,DODocumentCode,DOTransactionDate,DOShipmentDate,DODeliveredDate,DOPrintCount,DOLastPrintedDate,TotalWeight,TotalDimension,PrintCount,LastPrintedDate,DocumentStatusID,DocumentStatusName,MobileDocumentCode,PostedDate,CreatedDate,ModifiedDate,ChildSummaries";
        public static string Expand = "ChildSummaries($expand=ChildDetails)";

        #endregion

        #region Methods

        private async Task<Expression<Func<mvSalesOrderSwap, bool>>> GetFilter()
        {
            var warehouseIDs = await DbContext.GetDataTableProvider<mvWarehouseTableProvider>().GetData().Where(p => (p.TypeID == 2)).Select(p => p.ID).ToListAsync();

            Expression filter = null;
            var type = typeof(mvSalesOrderSwap);
            var param = Expression.Parameter(type, "param");

            var propWarehouseID = Expression.Property(param, "WarehouseID");
            foreach (var id in warehouseIDs)
            {
                var expr = Expression.MakeBinary(ExpressionType.Equal, propWarehouseID, Expression.Constant(id, type.GetProperty("WarehouseID").PropertyType));
                filter = (filter == null) ? expr : Expression.MakeBinary(ExpressionType.Or, filter, expr);
            }

            return Expression.Lambda<Func<mvSalesOrderSwap, bool>>(filter, param);
        }



        protected override Exception OnDownloadAllData(bool continueOnError) { return OnDownloadAllDataAsync(continueOnError).Result; }
        protected override Exception OnUploadAllData(bool continueOnError) { return OnUploadAllDataAsync(continueOnError).Result; }
        protected override Exception OnDownloadData(mvSalesOrderSwap obj, bool useTransaction) { return OnDownloadDataAsync(obj, useTransaction).Result; }
        protected override Exception OnUploadData(mvSalesOrderSwap obj, bool useTransaction) { return OnUploadDataAsync(obj, useTransaction).Result; }


        protected override async Task<Exception> OnDownloadAllDataAsync(bool continueOnError)
        {
            Exception exception = null;

            var salesOrderSwapTableProvider = DbContext.GetDataTableProvider<mvSalesOrderSwapTableProvider>();
            var salesOrderSwapServiceProvider = DataServiceContext.GetDataServiceProvider<mvSalesOrderSwapServiceProvider>();

            DateTime? syncDate = null;

            List<mvSalesOrderSwap> serverDataList = null;

            var minSyncDate = (DateTimeOffset?)await salesOrderSwapTableProvider.GetData().MinAsync(p => p.SyncDate);

            for (int i = 0; i < DbContext.SyncMaxAttempts; i++)
            {
                try
                {
                    if (!syncDate.HasValue) syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();

                    var query = salesOrderSwapServiceProvider.GetData().AddQueryOption("$select", Selector).AddQueryOption("$expand", Expand).Where(await GetFilter());
                                        
                    if (minSyncDate.HasValue)
                        query = query.Where(p => (p.CreatedDate > minSyncDate.Value) || ((p.ModifiedDate != null) && (p.ModifiedDate.Value > minSyncDate.Value)));

                    serverDataList = query.ToList();
                    break;
                }
                catch (Exception ex)
                {
                    if (i == (DbContext.SyncMaxAttempts - 1)) exception = ex;
                    else await Task.Delay(DbContext.SyncAttemptDelay);
                }
            }

            if (serverDataList != null)
            {
                int index = 0;
                foreach (var serverData in serverDataList)
                {
                    try
                    {
                        await ProcessLocalData(syncDate, 1, 1, serverData, null, salesOrderSwapTableProvider, true);
                    }
                    catch (Exception ex)
                    {
                        if (!continueOnError)
                        {
                            exception = ex;
                            break;
                        }
                    }

                    index++;
                }

                await DbContext.UpdateAllSyncDateAsync<mvSalesOrderSwap>(syncDate.Value);
            }

            return exception;
        }

        protected override async Task<Exception> OnUploadAllDataAsync(bool continueOnError)
        {
            Exception exception = null;

            var salesOrderSwapTableProvider = DbContext.GetDataTableProvider<mvSalesOrderSwapTableProvider>();
            var salesOrderSwapSummaryTableProvider = DbContext.GetDataTableProvider<mvSalesOrderSwapSummaryTableProvider>();
            var salesOrderSwapDetailsTableProvider = DbContext.GetDataTableProvider<mvSalesOrderSwapDetailsTableProvider>();
            var salesOrderSwapServiceProvider = DataServiceContext.GetDataServiceProvider<mvSalesOrderSwapServiceProvider>();

            DateTime? syncDate = null;

            var localDataList = await salesOrderSwapTableProvider.GetData().Where(p => (p.SyncDate == null)).Include(p => p.ChildSummaries).ThenInclude(q => q.ChildDetails).ToListAsync();

            int index = 0;
            foreach (var obj in localDataList)
            {
                var lastStatus = 1;
                var serverData = new mvSalesOrderSwap();

                serverData.CopyFrom(obj);
                serverData.ChildSummaries = new Collection<mvSalesOrderSwapSummary>();
                foreach (var summary in obj.ChildSummaries)
                {
                    var serverDataSummary = new mvSalesOrderSwapSummary();
                    serverDataSummary.CopyFrom(summary);
                    serverDataSummary.ChildDetails = new Collection<mvSalesOrderSwapDetails>();
                    if (summary.ChildDetails != null)
                    {
                        foreach (var details in summary.ChildDetails)
                        {
                            var serverDataDetails = new mvSalesOrderSwapDetails();
                            serverDataDetails.CopyFrom(details);

                            serverDataSummary.ChildDetails.Add(serverDataDetails);
                        }
                    }

                    serverData.ChildSummaries.Add(serverDataSummary);
                }

                serverData.DocumentCode = "";

                for (int i = 0; i < DbContext.SyncMaxAttempts; i++)
                {
                    try
                    {
                        if (!syncDate.HasValue) syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();

                        await salesOrderSwapServiceProvider.InsertDataAsync(serverData, true);

                        syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();
                        await ProcessLocalData(syncDate, 1, (i + 1), serverData, obj, salesOrderSwapTableProvider, true);
                        break;
                    }
                    catch (Exception ex)
                    {
                        if (i == (DbContext.SyncMaxAttempts - 1))
                        {
                            exception = ex;
                            lastStatus = 0;
                            try { await ProcessLocalData(syncDate, 0, (i + 1), serverData, obj, salesOrderSwapTableProvider, true); } catch (Exception) { }
                        }
                        else
                            await Task.Delay(DbContext.SyncAttemptDelay);
                    }
                }

                if ((lastStatus != 1) && !continueOnError)
                    break;

                index++;
            }

            return exception;
        }


        protected override async Task<Exception> OnDownloadDataAsync(mvSalesOrderSwap obj, bool useTransaction)
        {
            Exception exception = null;

            var salesOrderSwapTableProvider = DbContext.GetDataTableProvider<mvSalesOrderSwapTableProvider>();
            var salesOrderSwapServiceProvider = DataServiceContext.GetDataServiceProvider<mvSalesOrderSwapServiceProvider>();

            DateTime? syncDate = null;
            int status = 1;
            int attempts = 0;

            mvSalesOrderSwap serverData = null;

            for (int i = 0; i < DbContext.SyncMaxAttempts; i++)
            {
                try
                {
                    if (!syncDate.HasValue) syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();

                    serverData = salesOrderSwapServiceProvider.GetData().AddQueryOption("$select", Selector).AddQueryOption("$expand", Expand)
                        .Where(p => p.DocumentID.Equals(obj.DocumentID)).SingleOrDefault();
                    break;
                }
                catch (Exception ex)
                {
                    if (i == (DbContext.SyncMaxAttempts - 1)) { exception = ex; status = 0; }
                    else await Task.Delay(DbContext.SyncAttemptDelay);
                }
            }

            await ProcessLocalData(syncDate, status, attempts, serverData, obj, salesOrderSwapTableProvider, useTransaction);

            return exception;
        }

        protected override async Task<Exception> OnUploadDataAsync(mvSalesOrderSwap obj, bool useTransaction)
        {
            Exception exception = null;

            var salesOrderSwapTableProvider = DbContext.GetDataTableProvider<mvSalesOrderSwapTableProvider>();
            var salesOrderSwapServiceProvider = DataServiceContext.GetDataServiceProvider<mvSalesOrderSwapServiceProvider>();

            DateTime? syncDate = null;
            int status = 1;
            int attempts = 0;

            var serverData = new mvSalesOrderSwap();
            serverData.CopyFrom(obj);
            serverData.ChildSummaries = new Collection<mvSalesOrderSwapSummary>();
            foreach (var summary in obj.ChildSummaries)
            {
                var serverDataSummary = new mvSalesOrderSwapSummary();
                serverDataSummary.CopyFrom(summary);
                serverDataSummary.ChildDetails = new Collection<mvSalesOrderSwapDetails>();
                if (summary.ChildDetails != null)
                {
                    foreach (var details in summary.ChildDetails)
                    {
                        var serverDataDetails = new mvSalesOrderSwapDetails();
                        serverDataDetails.CopyFrom(details);

                        serverDataSummary.ChildDetails.Add(serverDataDetails);
                    }
                }

                serverData.ChildSummaries.Add(serverDataSummary);
            }

            serverData.DocumentCode = "";

            for (int i = 0; i < DbContext.SyncMaxAttempts; i++)
            {
                try
                {
                    if (!syncDate.HasValue) syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();
                    attempts++;

                    await salesOrderSwapServiceProvider.InsertDataAsync(serverData, useTransaction);

                    syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();
                    break;
                }
                catch (Exception ex)
                {
                    if (i == (DbContext.SyncMaxAttempts - 1)) { exception = ex; status = 0; }
                    else await Task.Delay(DbContext.SyncAttemptDelay);
                }
            }

            await ProcessLocalData(syncDate, status, attempts, serverData, obj, salesOrderSwapTableProvider, useTransaction);

            return exception;
        }



        private async Task ProcessLocalData(DateTime? syncDate, int status, int attempts, mvSalesOrderSwap serverData, mvSalesOrderSwap obj,
            mvSalesOrderSwapTableProvider tableProvider, bool useTransaction)
        {
            var localDate = (syncDate.HasValue) ? syncDate.Value : await DbContext.GetDatabaseUtcDateTimeAsync();
            mvSalesOrderSwap salesOrderSwap = null;

            if (serverData == null)
            {
                salesOrderSwap = new mvSalesOrderSwap();
                salesOrderSwap.DocumentID = obj.DocumentID;

                await tableProvider.DeleteDataAsync(salesOrderSwap, useTransaction);
            }
            else
            {
                var isInsert = false;
                salesOrderSwap = await tableProvider.GetDataAsync(serverData.DocumentID);
                if (salesOrderSwap == null)
                {
                    isInsert = true;
                    salesOrderSwap = new mvSalesOrderSwap();
                }

                salesOrderSwap.CopyFrom(serverData);
                salesOrderSwap.ChildSummaries = serverData.ChildSummaries;
                DbContext.SetSyncData(salesOrderSwap, syncDate, localDate, status, attempts);

                if (isInsert)
                    await tableProvider.InsertDataAsync(salesOrderSwap, useTransaction);
                else
                    await tableProvider.UpdateDataAsync(salesOrderSwap, useTransaction);

                if (obj != null)
                {
                    obj.CopyFrom(serverData);
                    DbContext.CopySyncData(obj, salesOrderSwap);
                }
            }
        }

        #endregion

    }

}
