// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:45:52
// Description   : vCityEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vCityEntityTypeConfig : IEntityTypeConfiguration<vCity>, IEdmEntityConfiguration<vCity>
    {

        #region Implements IEntityTypeConfiguration<vCity>
        
        public void Configure(EntityTypeBuilder<vCity> builder) { InternalConfigure(builder); }

        #endregion
        
        #region Implements IEdmEntityConfiguration<vCity>

        public string EntitySetName { get; } = "vCities";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vCity> builder) { InternalConfigureEdmEntity(builder); }

        #endregion
        
        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vCity
        {
            builder.ToTable("vCity");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.ID });
        }
        
        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vCity
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.ID });
        }

        #endregion

    }

}
