// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:45:26
// Description   : UserSiteEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AIO.IDOS3.Data.Entity
{

    public class UserSiteEntityTypeConfig : IEntityTypeConfiguration<UserSite>
    {

        #region Implements IEntityTypeConfiguration<UserSite>
        
        public void Configure(EntityTypeBuilder<UserSite> builder) { InternalConfigure(builder); }

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : UserSite
        {
            builder.ToTable("UserSite");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.SiteID, p.UserID });
        }
        
        #endregion

    }

}
