// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:46:36
// Description   : vStockReturnForSampleDetailsEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vStockReturnForSampleDetailsEntityTypeConfig : IEntityTypeConfiguration<vStockReturnForSampleDetails>, IEdmEntityConfiguration<vStockReturnForSampleDetails>
    {

        #region Implements IEntityTypeConfiguration<vStockReturnForSampleDetails>
        
        public void Configure(EntityTypeBuilder<vStockReturnForSampleDetails> builder) { InternalConfigure(builder); }

        #endregion
        
        #region Implements IEdmEntityConfiguration<vStockReturnForSampleDetails>

        public string EntitySetName { get; } = "vStockReturnForSampleDetails";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vStockReturnForSampleDetails> builder) { InternalConfigureEdmEntity(builder); }

        #endregion
        
        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vStockReturnForSampleDetails
        {
            builder.ToTable("vStockReturnForSampleDetails");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.DocumentID, p.ProductID, p.ProductLotID });
        }
        
        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vStockReturnForSampleDetails
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.DocumentID, p.ProductID, p.ProductLotID });
        }

        #endregion

    }

}
