// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:46:33
// Description   : vStockReceiveAsSampleDetailsEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vStockReceiveAsSampleDetailsEntityTypeConfig : IEntityTypeConfiguration<vStockReceiveAsSampleDetails>, IEdmEntityConfiguration<vStockReceiveAsSampleDetails>
    {

        #region Implements IEntityTypeConfiguration<vStockReceiveAsSampleDetails>
        
        public void Configure(EntityTypeBuilder<vStockReceiveAsSampleDetails> builder) { InternalConfigure(builder); }

        #endregion
        
        #region Implements IEdmEntityConfiguration<vStockReceiveAsSampleDetails>

        public string EntitySetName { get; } = "vStockReceiveAsSampleDetails";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vStockReceiveAsSampleDetails> builder) { InternalConfigureEdmEntity(builder); }

        #endregion
        
        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vStockReceiveAsSampleDetails
        {
            builder.ToTable("vStockReceiveAsSampleDetails");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.DocumentID, p.ProductID, p.ProductLotID });
        }
        
        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vStockReceiveAsSampleDetails
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.DocumentID, p.ProductID, p.ProductLotID });
        }

        #endregion

    }

}
