// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:46:24
// Description   : vStockItemStatusChangesSummaryEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vStockItemStatusChangesSummaryEntityTypeConfig : IEntityTypeConfiguration<vStockItemStatusChangesSummary>, IEdmEntityConfiguration<vStockItemStatusChangesSummary>
    {

        #region Implements IEntityTypeConfiguration<vStockItemStatusChangesSummary>
        
        public void Configure(EntityTypeBuilder<vStockItemStatusChangesSummary> builder) { InternalConfigure(builder); }

        #endregion
        
        #region Implements IEdmEntityConfiguration<vStockItemStatusChangesSummary>

        public string EntitySetName { get; } = "vStockItemStatusChangesSummaries";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vStockItemStatusChangesSummary> builder) { InternalConfigureEdmEntity(builder); }

        #endregion
        
        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vStockItemStatusChangesSummary
        {
            builder.ToTable("vStockItemStatusChangesSummary");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.DocumentID, p.ProductID });
        }
        
        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vStockItemStatusChangesSummary
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.DocumentID, p.ProductID });
        }

        #endregion

    }

}
