// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:46:19
// Description   : vSiteAccountingEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vSiteAccountingEntityTypeConfig : IEntityTypeConfiguration<vSiteAccounting>, IEdmEntityConfiguration<vSiteAccounting>
    {

        #region Implements IEntityTypeConfiguration<vSiteAccounting>
        
        public void Configure(EntityTypeBuilder<vSiteAccounting> builder) { InternalConfigure(builder); }

        #endregion
        
        #region Implements IEdmEntityConfiguration<vSiteAccounting>

        public string EntitySetName { get; } = "vSiteAccountings";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vSiteAccounting> builder) { InternalConfigureEdmEntity(builder); }

        #endregion
        
        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vSiteAccounting
        {
            builder.ToTable("vSiteAccounting");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.SiteID });
        }
        
        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vSiteAccounting
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.SiteID });
        }

        #endregion

    }

}
