// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:46:27
// Description   : vStockOnHandAvailableEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vStockOnHandAvailableEntityTypeConfig : IEntityTypeConfiguration<vStockOnHandAvailable>, IEdmEntityConfiguration<vStockOnHandAvailable>
    {

        #region Implements IEntityTypeConfiguration<vStockOnHandAvailable>
        
        public void Configure(EntityTypeBuilder<vStockOnHandAvailable> builder) { InternalConfigure(builder); }

        #endregion
        
        #region Implements IEdmEntityConfiguration<vStockOnHandAvailable>

        public string EntitySetName { get; } = "vStockOnHandAvailables";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vStockOnHandAvailable> builder) { InternalConfigureEdmEntity(builder); }

        #endregion
        
        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vStockOnHandAvailable
        {
            builder.ToTable("vStockOnHandAvailable");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.WarehouseID, p.ProductID, p.ProductLotID });
        }
        
        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vStockOnHandAvailable
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.WarehouseID, p.ProductID, p.ProductLotID });
        }

        #endregion

    }

}
