// ===================================================================================
// Author        : System
// Created date  : 27 Oct 2020 00:25:27
// Description   : mvCustomerBillGroupSyncProvider partial class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Mobile.Data.Entity
{

    public partial class mvCustomerBillGroupSyncProvider : DataSyncProvider<mvCustomerBillGroup>
    {

        #region Properties
        
        public static string Selector = "ID,Code,Name,BillGroup,HeadID,HeadCode,HeadName,Head,CollectorID,ContactPerson,Address1,Address2,Address3,Address,CityID,City,StateProvinceID,StateProvince,CountryID,CountryName,ZipCode,Phone1,Phone2,Phone3,Fax,Email,Longitude,Latitude,TaxIDNumber,TaxIDName,TaxContactPerson,IsTaxAddressSameAsAddress,TaxAddress1,TaxAddress2,TaxAddress3,TaxAddress,TaxCityID,TaxCity,TaxStateProvinceID,TaxStateProvince,TaxCountryID,TaxCountryName,TaxZipCode,TaxPhone1,TaxPhone2,TaxPhone3,TaxFax,TaxEmail,TaxLongitude,TaxLatitude,CollectionRoutePlanWeek1,CollectionRoutePlanWeek2,CollectionRoutePlanWeek3,CollectionRoutePlanWeek4,CollectionRoutePlanDay1,CollectionRoutePlanDay2,CollectionRoutePlanDay3,CollectionRoutePlanDay4,CollectionRoutePlanDay5,CollectionRoutePlanDay6,CollectionRoutePlanDay7,StatusID,StatusName,CreatedDate,ModifiedDate,IsDeleted";
        
        #endregion
        
        #region Methods
        
        private async Task<Expression<Func<mvCustomerBillGroup, bool>>> GetFilter()
        {
            var collectorIDs = await DbContext.GetDataTableProvider<mvCollectorTableProvider>().GetData().Select(p => p.ID).ToListAsync();

            if (collectorIDs.Count == 0)
                return (p => false);

            Expression filter = null;
            var type = typeof(mvCustomerBillGroup);
            var param = Expression.Parameter(type, "param");

            var propCollectorID = Expression.Property(param, "CollectorID");
            foreach (var id in collectorIDs)
            {
                var expr = Expression.MakeBinary(ExpressionType.Equal, propCollectorID, Expression.Constant(id, type.GetProperty("CollectorID").PropertyType));
                filter = (filter == null) ? expr : Expression.MakeBinary(ExpressionType.Or, filter, expr);
            }

            var propStatusID = Expression.Property(param, "StatusID");
            var addExpr = Expression.MakeBinary(ExpressionType.Equal, propStatusID, Expression.Constant(1, type.GetProperty("StatusID").PropertyType)); // Active
            filter = (filter == null) ? addExpr : Expression.MakeBinary(ExpressionType.And, filter, addExpr);

            return Expression.Lambda<Func<mvCustomerBillGroup, bool>>(filter, param);
        }
        
        
        
        protected override Exception OnDownloadAllData(bool continueOnError) { return OnDownloadAllDataAsync(continueOnError).Result; }
        protected override Exception OnUploadAllData(bool continueOnError) { return OnUploadAllDataAsync(continueOnError).Result; }
        protected override Exception OnDownloadData(mvCustomerBillGroup obj, bool useTransaction) { return OnDownloadDataAsync(obj, useTransaction).Result; }
        protected override Exception OnUploadData(mvCustomerBillGroup obj, bool useTransaction) { return OnUploadDataAsync(obj, useTransaction).Result; }


        protected override async Task<Exception> OnDownloadAllDataAsync(bool continueOnError)
        {
            Exception exception = null;

            var customerBillGroupTableProvider = DbContext.GetDataTableProvider<mvCustomerBillGroupTableProvider>();
            var customerBillGroupServiceProvider = DataServiceContext.GetDataServiceProvider<mvCustomerBillGroupServiceProvider>();

            DateTime? syncDate = null;

            List<mvCustomerBillGroup> serverDataList = null;

            var minSyncDate = (DateTimeOffset?)await customerBillGroupTableProvider.GetData().MinAsync(p => p.SyncDate);

            for (int i = 0; i < DbContext.SyncMaxAttempts; i++)
            {
                try
                {
                    if (!syncDate.HasValue) syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();

                    var query = customerBillGroupServiceProvider.GetData().AddQueryOption("$select", Selector).Where(await GetFilter());

                    if (minSyncDate.HasValue)
                        query = query.Where(p => (p.CreatedDate > minSyncDate.Value) || ((p.ModifiedDate != null) && (p.ModifiedDate.Value > minSyncDate.Value)));
                        
                    serverDataList = query.ToList();
                    break;
                }
                catch (Exception ex)
                {
                    if (i == (DbContext.SyncMaxAttempts - 1)) exception = ex;
                    else await Task.Delay(DbContext.SyncAttemptDelay);
                }
            }

            if (serverDataList != null)
            {
                if (serverDataList.Count > 0)
                {
                    var collectors = await DbContext.GetDataTableProvider<mvCollectorTableProvider>().GetData().ToListAsync();

                    int index = 0;
                    foreach (var serverData in serverDataList)
                    {
                        try
                        {
                            var collector = collectors.Where(p => p.ID.Equals(serverData.CollectorID)).SingleOrDefault();

                            AssignFromLocalData(serverData, collector);

                            await ProcessLocalData(syncDate, 1, 1, serverData, null, customerBillGroupTableProvider, true);
                        }
                        catch (Exception ex)
                        {
                            if (!continueOnError)
                            {
                                exception = ex;
                                break;
                            }
                        }

                        index++;
                    }
                }

                await DbContext.UpdateAllSyncDateAsync<mvCustomerBillGroup>(syncDate.Value);
            }

            return exception;
        }
        
        protected override async Task<Exception> OnUploadAllDataAsync(bool continueOnError)
        {
            Exception exception = null;

            var customerBillGroupTableProvider = DbContext.GetDataTableProvider<mvCustomerBillGroupTableProvider>();
            var customerBillGroupServiceProvider = DataServiceContext.GetDataServiceProvider<mvCustomerBillGroupServiceProvider>();

            DateTime? syncDate = null;

            var localDataList = await customerBillGroupTableProvider.GetData().Where(p => (p.SyncDate == null) && !p.IsDeleted).ToListAsync();

            int index = 0;
            foreach (var obj in localDataList)
            {
                var lastStatus = 1;
                var serverData = new mvCustomerBillGroup();
                serverData.CopyFrom(obj);

                if (serverData.SyncDate == null)
                    serverData.Code = "";

                for (int i = 0; i < DbContext.SyncMaxAttempts; i++)
                {
                    try
                    {
                        if (!syncDate.HasValue) syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();

                        await customerBillGroupServiceProvider.InsertDataAsync(serverData, true);
                        
                        syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();
                        await ProcessLocalData(syncDate, 1, (i + 1), serverData, obj, customerBillGroupTableProvider, true);
                        break;
                    }
                    catch (Exception ex)
                    {
                        if (i == (DbContext.SyncMaxAttempts - 1))
                        {
                            exception = ex;
                            lastStatus = 0;
                            try { await ProcessLocalData(syncDate, 0, (i + 1), serverData, obj, customerBillGroupTableProvider, true); } catch (Exception) { }
                        }
                        else
                            await Task.Delay(DbContext.SyncAttemptDelay);
                    }
                }

                if ((lastStatus != 1) && !continueOnError)
                    break;

                index++;
            }

            return exception;
        }


        protected override async Task<Exception> OnDownloadDataAsync(mvCustomerBillGroup obj, bool useTransaction)
        {
            Exception exception = null;

            var customerBillGroupTableProvider = DbContext.GetDataTableProvider<mvCustomerBillGroupTableProvider>();
            var customerBillGroupServiceProvider = DataServiceContext.GetDataServiceProvider<mvCustomerBillGroupServiceProvider>();

            DateTime? syncDate = null;
            int status = 1;
            int attempts = 0;

            mvCustomerBillGroup serverData = null;

            for (int i = 0; i < DbContext.SyncMaxAttempts; i++)
            {
                try
                {
                    if (!syncDate.HasValue) syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();

                    serverData = customerBillGroupServiceProvider.GetData().AddQueryOption("$select", Selector)
                        .Where(p => p.ID.Equals(obj.ID)).SingleOrDefault();
                    break;
                }
                catch (Exception ex)
                {
                    if (i == (DbContext.SyncMaxAttempts - 1)) { exception = ex; status = 0; }
                    else await Task.Delay(DbContext.SyncAttemptDelay);
                }
            }

            if (serverData != null)
            {
                var collector = await DbContext.GetDataTableProvider<mvCollectorTableProvider>().GetDataAsync(serverData.CollectorID);

                AssignFromLocalData(serverData, collector);
            }

            await ProcessLocalData(syncDate, status, attempts, serverData, obj, customerBillGroupTableProvider, useTransaction);

            return exception;
        }

        protected override async Task<Exception> OnUploadDataAsync(mvCustomerBillGroup obj, bool useTransaction)
        {
            Exception exception = null;

            var customerBillGroupTableProvider = DbContext.GetDataTableProvider<mvCustomerBillGroupTableProvider>();
            var customerBillGroupServiceProvider = DataServiceContext.GetDataServiceProvider<mvCustomerBillGroupServiceProvider>();

            DateTime? syncDate = null;
            int status = 1;
            int attempts = 0;

            var serverData = new mvCustomerBillGroup();
            serverData.CopyFrom(obj);

            if (serverData.SyncDate == null)
                serverData.Code = "";

            for (int i = 0; i < DbContext.SyncMaxAttempts; i++)
            {
                try
                {
                    if (!syncDate.HasValue) syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();
                    attempts++;

                    await customerBillGroupServiceProvider.InsertDataAsync(serverData, useTransaction);
                    
                    syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();
                    break;
                }
                catch (Exception ex)
                {
                    if (i == (DbContext.SyncMaxAttempts - 1)) { exception = ex; status = 0; }
                    else await Task.Delay(DbContext.SyncAttemptDelay);
                }
            }

            await ProcessLocalData(syncDate, status, attempts, serverData, obj, customerBillGroupTableProvider, useTransaction);

            return exception;
        }



        private async Task ProcessLocalData(DateTime? syncDate, int status, int attempts, mvCustomerBillGroup serverData, mvCustomerBillGroup obj,
            mvCustomerBillGroupTableProvider tableProvider, bool useTransaction)
        {
            var localDate = (syncDate.HasValue) ? syncDate.Value : await DbContext.GetDatabaseUtcDateTimeAsync();
            mvCustomerBillGroup customerBillGroup = null;

            if (serverData == null)
            {
                customerBillGroup = new mvCustomerBillGroup();
                customerBillGroup.ID = obj.ID;

                await tableProvider.DeleteDataAsync(customerBillGroup, useTransaction);
            }
            else
            {
                var isInsert = false;
                var isDelete = false;
                customerBillGroup = await tableProvider.GetDataAsync(serverData.ID);
                if (customerBillGroup == null)
                {
                    isInsert = true;
                    customerBillGroup = new mvCustomerBillGroup();
                }                
                else if (customerBillGroup.IsDeleted)
                    isDelete = true;                    

                customerBillGroup.CopyFrom(serverData);
                DbContext.SetSyncData(customerBillGroup, syncDate, localDate, status, attempts);

                if (isInsert)
                    await tableProvider.InsertDataAsync(customerBillGroup, useTransaction);
                else if (isDelete)
                    await tableProvider.DeleteDataAsync(customerBillGroup, useTransaction);
                else
                    await tableProvider.UpdateDataAsync(customerBillGroup, useTransaction);

                if (obj != null)
                {
                    obj.CopyFrom(serverData);
                    DbContext.CopySyncData(obj, customerBillGroup);
                }
            }
        }

        private void AssignFromLocalData(mvCustomerBillGroup serverData, mvCollector collector)
        {
            if (collector != null)
            {
                serverData.CollectorCode = collector.Code;
                serverData.CollectorName = collector.Name;
                serverData.Collector = collector.Collector;
                serverData.IsCollectedByHeadOffice = collector.IsHeadOffice;
                serverData.CollectedBySiteID = collector.SiteID;
                serverData.CollectedBySiteCode = collector.SiteCode;
                serverData.CollectedBySiteName = collector.SiteName;
                serverData.CollectedBySite = collector.Site;
                serverData.CollectedByAreaID = collector.AreaID;
                serverData.CollectedByAreaCode = collector.AreaCode;
                serverData.CollectedByAreaName = collector.AreaName;
                serverData.CollectedByArea = collector.Area;
                serverData.CollectedByRegionID = collector.RegionID;
                serverData.CollectedByRegionCode = collector.RegionCode;
                serverData.CollectedByRegionName = collector.RegionName;
                serverData.CollectedByRegion = collector.Region;
                serverData.CollectedByTerritoryID = collector.TerritoryID;
                serverData.CollectedByTerritoryCode = collector.TerritoryCode;
                serverData.CollectedByTerritoryName = collector.TerritoryName;
                serverData.CollectedByTerritory = collector.Territory;
                serverData.CollectedByCompanyID = collector.CompanyID;
                serverData.CollectedByCompanyCode = collector.CompanyCode;
                serverData.CollectedByCompanyName = collector.CompanyName;
                serverData.CollectedByCompany = collector.Company;
                serverData.CollectedBySiteDistributionTypeID = collector.SiteDistributionTypeID;
                serverData.CollectedBySiteDistributionTypeName = collector.SiteDistributionTypeName;
            }
        }

        #endregion

    }

}
