// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:45:57
// Description   : vDailySalesReportEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vDailySalesReportEntityTypeConfig : IEntityTypeConfiguration<vDailySalesReport>, IEdmEntityConfiguration<vDailySalesReport>
    {

        #region Implements IEntityTypeConfiguration<vDailySalesReport>

        public void Configure(EntityTypeBuilder<vDailySalesReport> builder) { InternalConfigure(builder); }

        #endregion

        #region Implements IEdmEntityConfiguration<vDailySalesReport>

        public string EntitySetName { get; } = "vDailySalesReports";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vDailySalesReport> builder) { InternalConfigureEdmEntity(builder); }

        #endregion
        
        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vDailySalesReport
        {
            builder.ToTable("vDailySalesReport");

            //// Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.RowArea1, p.RowArea2, p.RowArea3, p.ColumnArea1, p.ColumnArea2, p.ColumnArea3, p.ColumnArea4 });
        }

        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vDailySalesReport
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.RowArea1, p.RowArea2, p.RowArea3, p.ColumnArea1, p.ColumnArea2, p.ColumnArea3, p.ColumnArea4 });
        }

        #endregion

    }

}
