// ===================================================================================
// Author        : System
// Created date  : 09 Aug 2020 16:32:39
// Description   : UserTableProvider partial class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Wismapi.Data;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public partial class UserTableProvider : DataTableProvider<User>
    {

        #region Methods

        public User GetDataByName(string name)
        {
            return GetData().SingleOrDefault(p => p.Name.Equals(name, StringComparison.OrdinalIgnoreCase));
        }

        public IList<User> GetDataBySiteID(Guid siteID)
        {
            return GetData().Where(p => (p.SiteID == siteID)).ToList();
        }



        protected override async Task OnBeginInsertDataAsync(BeginOperationDataEventArgs<User> e)
        {
            e.Data.CreatedDate = await DbContext.GetDatabaseUtcDateTimeAsync();

            var authenticatedUser = ((MainDbContext)DbContext).GetAuthenticatedUser();
            if (authenticatedUser != null)
                e.Data.ModifiedByUserID = authenticatedUser.ID;

            await base.OnBeginInsertDataAsync(e);
        }

        protected override async Task OnBeginUpdateDataAsync(BeginOperationDataEventArgs<User> e)
        {
            e.Data.ModifiedDate = await DbContext.GetDatabaseUtcDateTimeAsync();
            
            var authenticatedUser = ((MainDbContext)DbContext).GetAuthenticatedUser();
            if (authenticatedUser != null)
                e.Data.ModifiedByUserID = authenticatedUser.ID;

            await base.OnBeginUpdateDataAsync(e);
        }

        protected override async Task OnBeginDeleteDataAsync(BeginOperationDataEventArgs<User> e)
        {
            e.Data.ModifiedDate = await DbContext.GetDatabaseUtcDateTimeAsync();

            await base.OnBeginDeleteDataAsync(e);
        }

        #endregion
        
    }

}
