// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:46:02
// Description   : vInvoiceMainDetailBARSEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vInvoiceMainDetailBARSEntityTypeConfig : IEntityTypeConfiguration<vInvoiceMainDetailBARS>, IEdmEntityConfiguration<vInvoiceMainDetailBARS>
    {

        #region Implements IEntityTypeConfiguration<vInvoiceMainDetailBARS>
        
        public void Configure(EntityTypeBuilder<vInvoiceMainDetailBARS> builder) { InternalConfigure(builder); }

        #endregion
        
        #region Implements IEdmEntityConfiguration<vInvoiceMainDetailBARS>

        public string EntitySetName { get; } = "vInvoiceMainDetailBARS";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vInvoiceMainDetailBARS> builder) { InternalConfigureEdmEntity(builder); }

        #endregion
        
        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vInvoiceMainDetailBARS
        {
            builder.ToTable("vInvoiceMainDetailBARS");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.InvoiceDocumentID, p.BARSDocumentID });
        }
        
        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vInvoiceMainDetailBARS
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.InvoiceDocumentID, p.BARSDocumentID });
        }

        #endregion

    }

}
