// ===================================================================================
// Author        : System
// Created date  : 06 Aug 2020 17:31:00
// Description   : BillAndReceiptStatementDetailsEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AIO.IDOS3.Data.Entity
{

    public class BillAndReceiptStatementDetailsEntityTypeConfig : IEntityTypeConfiguration<BillAndReceiptStatementDetails>
    {

        #region Implements IEntityTypeConfiguration<BillAndReceiptStatementDetails>
        
        public void Configure(EntityTypeBuilder<BillAndReceiptStatementDetails> builder) { InternalConfigure(builder); }

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : BillAndReceiptStatementDetails
        {
            builder.ToTable("BillAndReceiptStatementDetails");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.DocumentID, p.InvoiceDocumentID });
        }
        
        #endregion

    }

}
