// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:46:02
// Description   : vInvoiceMainEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vInvoiceMainEntityTypeConfig : IEntityTypeConfiguration<vInvoiceMain>, IEdmEntityConfiguration<vInvoiceMain>
    {

        #region Implements IEntityTypeConfiguration<vInvoiceMain>
        
        public void Configure(EntityTypeBuilder<vInvoiceMain> builder) { InternalConfigure(builder); }

        #endregion
        
        #region Implements IEdmEntityConfiguration<vInvoiceMain>

        public string EntitySetName { get; } = "vInvoiceMains";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vInvoiceMain> builder) { InternalConfigureEdmEntity(builder); }

        #endregion
        
        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vInvoiceMain
        {
            builder.ToTable("vInvoiceMain");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.DocumentID });
        }
        
        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vInvoiceMain
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.DocumentID });
        }

        #endregion

    }

}
