// ===================================================================================
// Author        : System
// Created date  : 25 Sep 2020 00:13:26
// Description   : mvCollectionCallSyncProvider partial class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Mobile.Data.Entity
{

    public partial class mvCollectionCallSyncProvider : DataSyncProvider<mvCollectionCall>
    {

        #region Properties
        
        public static string Selector = "ID,ActivityID,ActivityDate,ReferenceID,IsReferenceCustomerID,ReferenceCode,ReferenceName,Reference,CheckedInTime,CheckedInLongitude,CheckedInLatitude,CheckedOutTime,CheckedOutLongitude,CheckedOutLatitude,FirstCheckedInTime,FirstCheckedInLongitude,FirstCheckedInLatitude,FirstCheckedOutTime,FirstCheckedOutLongitude,FirstCheckedOutLatitude,NoCollectionReasonID,NoCollectionReasonName,ClosedOfficePhotoEvidence,CreatedDate,ModifiedDate";
        
        #endregion
        
        #region Methods
        
        private async Task<Expression<Func<mvCollectionCall, bool>>> GetFilter()
        {
            await Task.CompletedTask;
            throw new NotImplementedException();
        }
        
        
        
        protected override Exception OnDownloadAllData(bool continueOnError) { return OnDownloadAllDataAsync(continueOnError).Result; }
        protected override Exception OnUploadAllData(bool continueOnError) { return OnUploadAllDataAsync(continueOnError).Result; }
        protected override Exception OnDownloadData(mvCollectionCall obj, bool useTransaction) { return OnDownloadDataAsync(obj, useTransaction).Result; }
        protected override Exception OnUploadData(mvCollectionCall obj, bool useTransaction) { return OnUploadDataAsync(obj, useTransaction).Result; }


        protected override async Task<Exception> OnDownloadAllDataAsync(bool continueOnError)
        {
            Exception exception = null;

            var salesCallTableProvider = DbContext.GetDataTableProvider<mvCollectionCallTableProvider>();
            var salesCallServiceProvider = DataServiceContext.GetDataServiceProvider<mvCollectionCallServiceProvider>();

            DateTime? syncDate = null;

            List<mvCollectionCall> serverDataList = null;

            var minSyncDate = (DateTimeOffset?)await salesCallTableProvider.GetData().MinAsync(p => p.SyncDate);

            for (int i = 0; i < DbContext.SyncMaxAttempts; i++)
            {
                try
                {
                    if (!syncDate.HasValue) syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();

                    var query = salesCallServiceProvider.GetData().AddQueryOption("$select", Selector).Where(await GetFilter());

                    if (minSyncDate.HasValue)
                        query = query.Where(p => (p.CreatedDate > minSyncDate.Value) || ((p.ModifiedDate != null) && (p.ModifiedDate.Value > minSyncDate.Value)));
                        
                    serverDataList = query.ToList();
                    break;
                }
                catch (Exception ex)
                {
                    if (i == (DbContext.SyncMaxAttempts - 1)) exception = ex;
                    else await Task.Delay(DbContext.SyncAttemptDelay);
                }
            }

            if (serverDataList != null)
            {
                int index = 0;
                foreach (var serverData in serverDataList)
                {
                    try
                    {
                        await ProcessLocalData(syncDate, 1, 1, serverData, null, salesCallTableProvider, true);
                    }
                    catch (Exception ex)
                    {
                        if (!continueOnError)
                        {
                            exception = ex;
                            break;
                        }
                    }

                    index++;
                }
                
                await DbContext.UpdateAllSyncDateAsync<mvCollectionCall>(syncDate.Value);
            }

            return exception;
        }
        
        protected override async Task<Exception> OnUploadAllDataAsync(bool continueOnError)
        {
            Exception exception = null;

            var salesCallTableProvider = DbContext.GetDataTableProvider<mvCollectionCallTableProvider>();
            var salesCallServiceProvider = DataServiceContext.GetDataServiceProvider<mvCollectionCallServiceProvider>();

            DateTime? syncDate = null;

            var localDataList = await salesCallTableProvider.GetData().Where(p => (p.SyncDate == null)).ToListAsync();

            int index = 0;
            foreach (var obj in localDataList)
            {
                var lastStatus = 1;
                var serverData = new mvCollectionCall();
                serverData.CopyFrom(obj);

                for (int i = 0; i < DbContext.SyncMaxAttempts; i++)
                {
                    try
                    {
                        if (!syncDate.HasValue) syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();

                        await salesCallServiceProvider.InsertDataAsync(serverData, true);
                        
                        syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();
                        await ProcessLocalData(syncDate, 1, (i + 1), serverData, obj, salesCallTableProvider, true);
                        break;
                    }
                    catch (Exception ex)
                    {
                        if (i == (DbContext.SyncMaxAttempts - 1))
                        {
                            exception = ex;
                            lastStatus = 0;
                            try { await ProcessLocalData(syncDate, 0, (i + 1), serverData, obj, salesCallTableProvider, true); } catch (Exception) { }
                        }
                        else
                            await Task.Delay(DbContext.SyncAttemptDelay);
                    }
                }

                if ((lastStatus != 1) && !continueOnError)
                    break;

                index++;
            }

            return exception;
        }


        protected override async Task<Exception> OnDownloadDataAsync(mvCollectionCall obj, bool useTransaction)
        {
            Exception exception = null;

            var salesCallTableProvider = DbContext.GetDataTableProvider<mvCollectionCallTableProvider>();
            var salesCallServiceProvider = DataServiceContext.GetDataServiceProvider<mvCollectionCallServiceProvider>();

            DateTime? syncDate = null;
            int status = 1;
            int attempts = 0;

            mvCollectionCall serverData = null;

            for (int i = 0; i < DbContext.SyncMaxAttempts; i++)
            {
                try
                {
                    if (!syncDate.HasValue) syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();

                    serverData = salesCallServiceProvider.GetData().AddQueryOption("$select", Selector)
                        .Where(p => p.ID.Equals(obj.ID)).SingleOrDefault();
                    break;
                }
                catch (Exception ex)
                {
                    if (i == (DbContext.SyncMaxAttempts - 1)) { exception = ex; status = 0; }
                    else await Task.Delay(DbContext.SyncAttemptDelay);
                }
            }

            await ProcessLocalData(syncDate, status, attempts, serverData, obj, salesCallTableProvider, useTransaction);

            return exception;
        }

        protected override async Task<Exception> OnUploadDataAsync(mvCollectionCall obj, bool useTransaction)
        {
            Exception exception = null;

            var salesCallTableProvider = DbContext.GetDataTableProvider<mvCollectionCallTableProvider>();
            var salesCallServiceProvider = DataServiceContext.GetDataServiceProvider<mvCollectionCallServiceProvider>();

            DateTime? syncDate = null;
            int status = 1;
            int attempts = 0;

            var serverData = new mvCollectionCall();
            serverData.CopyFrom(obj);

            for (int i = 0; i < DbContext.SyncMaxAttempts; i++)
            {
                try
                {
                    if (!syncDate.HasValue) syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();
                    attempts++;

                    await salesCallServiceProvider.InsertDataAsync(serverData, useTransaction);
                    
                    syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();
                    break;
                }
                catch (Exception ex)
                {
                    if (i == (DbContext.SyncMaxAttempts - 1)) { exception = ex; status = 0; }
                    else await Task.Delay(DbContext.SyncAttemptDelay);
                }
            }

            await ProcessLocalData(syncDate, status, attempts, serverData, obj, salesCallTableProvider, useTransaction);

            return exception;
        }



        private async Task ProcessLocalData(DateTime? syncDate, int status, int attempts, mvCollectionCall serverData, mvCollectionCall obj,
            mvCollectionCallTableProvider tableProvider, bool useTransaction)
        {
            var localDate = (syncDate.HasValue) ? syncDate.Value : await DbContext.GetDatabaseUtcDateTimeAsync();
            mvCollectionCall salesCall = null;

            if (serverData == null)
            {
                salesCall = new mvCollectionCall();
                salesCall.ID = obj.ID;

                await tableProvider.DeleteDataAsync(salesCall, useTransaction);
            }
            else
            {
                var isInsert = false;
                salesCall = await tableProvider.GetDataAsync(serverData.ID);
                if (salesCall == null)
                {
                    isInsert = true;
                    salesCall = new mvCollectionCall();
                }                

                salesCall.CopyFrom(serverData);
                DbContext.SetSyncData(salesCall, syncDate, localDate, status, attempts);

                if (isInsert)
                    await tableProvider.InsertDataAsync(salesCall, useTransaction);
                else
                    await tableProvider.UpdateDataAsync(salesCall, useTransaction);

                if (obj != null)
                {
                    obj.CopyFrom(serverData);
                    DbContext.CopySyncData(obj, salesCall);
                }
            }
        }

        #endregion

    }

}
