// ===================================================================================
// Author        : System
// Created date  : 08 Oct 2020 05:23:03
// Description   : mvPaymentCollectionEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using AIO.IDOS3.Data.Entity;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Mobile.Data.Entity
{

    public class mvPaymentCollectionEntityTypeConfig : IEntityTypeConfiguration<mvPaymentCollection>, IEdmEntityConfiguration<mvPaymentCollection>
    {

        #region Fields

        private vPaymentCollectionEntityTypeConfig parentConfig = new vPaymentCollectionEntityTypeConfig();

        #endregion

        #region Implements IEntityTypeConfiguration<mvPaymentCollection>

        public void Configure(EntityTypeBuilder<mvPaymentCollection> builder) { parentConfig.InternalConfigure(builder); }

        #endregion

        #region Implements IEdmEntityConfiguration<mvPaymentCollection>

        public string EntitySetName { get { return parentConfig.EntitySetName; } }

        public void ConfigureEdmEntity(EntityTypeConfiguration<mvPaymentCollection> builder) { parentConfig.InternalConfigureEdmEntity(builder); }

        #endregion

    }

}
