// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:45:06
// Description   : InvoiceAccountReceivableEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AIO.IDOS3.Data.Entity
{

    public class InvoiceAccountReceivableEntityTypeConfig : IEntityTypeConfiguration<InvoiceAccountReceivable>
    {

        #region Implements IEntityTypeConfiguration<InvoiceAccountReceivable>
        
        public void Configure(EntityTypeBuilder<InvoiceAccountReceivable> builder) { InternalConfigure(builder); }

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : InvoiceAccountReceivable
        {
            builder.ToTable("InvoiceAccountReceivable");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.InvoiceDocumentID });
        }
        
        #endregion

    }

}
