// ===================================================================================
// Author        : System
// Created date  : 24 Sep 2020 05:15:07
// Description   : mvSalesmanProductEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using AIO.IDOS3.Data.Entity;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Mobile.Data.Entity
{

    public class mvSalesmanProductEntityTypeConfig : IEntityTypeConfiguration<mvSalesmanProduct>, IEdmEntityConfiguration<mvSalesmanProduct>
    {

        #region Fields

        private vSalesmanProductEntityTypeConfig parentConfig = new vSalesmanProductEntityTypeConfig();

        #endregion

        #region Implements IEntityTypeConfiguration<mvSalesmanProduct>

        public void Configure(EntityTypeBuilder<mvSalesmanProduct> builder) { parentConfig.InternalConfigure(builder); }

        #endregion

        #region Implements IEdmEntityConfiguration<mvSalesmanProduct>

        public string EntitySetName { get { return parentConfig.EntitySetName; } }

        public void ConfigureEdmEntity(EntityTypeConfiguration<mvSalesmanProduct> builder) { parentConfig.InternalConfigureEdmEntity(builder); }

        #endregion

    }

}
