// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:46:31
// Description   : vStockReceiptDetailsEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vStockReceiptDetailsEntityTypeConfig : IEntityTypeConfiguration<vStockReceiptDetails>, IEdmEntityConfiguration<vStockReceiptDetails>
    {

        #region Implements IEntityTypeConfiguration<vStockReceiptDetails>
        
        public void Configure(EntityTypeBuilder<vStockReceiptDetails> builder) { InternalConfigure(builder); }

        #endregion
        
        #region Implements IEdmEntityConfiguration<vStockReceiptDetails>

        public string EntitySetName { get; } = "vStockReceiptDetails";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vStockReceiptDetails> builder) { InternalConfigureEdmEntity(builder); }

        #endregion
        
        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vStockReceiptDetails
        {
            builder.ToTable("vStockReceiptDetails");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.DocumentID, p.ProductID, p.ProductLotID });
        }
        
        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vStockReceiptDetails
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.DocumentID, p.ProductID, p.ProductLotID });
        }

        #endregion

    }

}
