// ===================================================================================
// Author        : System
// Created date  : 25 Sep 2020 00:13:24
// Description   : mvCustomerStockRecordEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using AIO.IDOS3.Data.Entity;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Mobile.Data.Entity
{

    public class mvCustomerStockRecordEntityTypeConfig : IEntityTypeConfiguration<mvCustomerStockRecord>, IEdmEntityConfiguration<mvCustomerStockRecord>
    {

        #region Fields

        private vCustomerStockRecordEntityTypeConfig parentConfig = new vCustomerStockRecordEntityTypeConfig();

        #endregion

        #region Implements IEntityTypeConfiguration<mvCustomerStockRecord>

        public void Configure(EntityTypeBuilder<mvCustomerStockRecord> builder) { parentConfig.InternalConfigure(builder); }

        #endregion

        #region Implements IEdmEntityConfiguration<mvCustomerStockRecord>

        public string EntitySetName { get { return parentConfig.EntitySetName; } }

        public void ConfigureEdmEntity(EntityTypeConfiguration<mvCustomerStockRecord> builder) { parentConfig.InternalConfigureEdmEntity(builder); }

        #endregion

    }

}
