// ===================================================================================
// Author        : System
// Created date  : 25 Sep 2020 00:13:24
// Description   : mvCustomerStockRecordSyncProvider partial class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Mobile.Data.Entity
{

    public partial class mvCustomerStockRecordSyncProvider : DataSyncProvider<mvCustomerStockRecord>
    {

        #region Properties
        
        public static string Selector = "CustomerID,RecordDateID,ProductID,ProductBrandID,SalesCallID,QtyConvL,QtyConvM,QtyConvS,Qty,QtyRecordConv,QtyRecommendedConvL,QtyRecommendedConvM,QtyRecommendedConvS,QtyRecommended,QtyRecommendedConv,CreatedDate";
        
        #endregion
        
        #region Methods
        
        private async Task<Expression<Func<mvCustomerStockRecord, bool>>> GetFilter()
        {
            await Task.CompletedTask;
            throw new NotImplementedException();
        }
        
        
        
        protected override Exception OnDownloadAllData(bool continueOnError) { return OnDownloadAllDataAsync(continueOnError).Result; }
        protected override Exception OnUploadAllData(bool continueOnError) { return OnUploadAllDataAsync(continueOnError).Result; }
        protected override Exception OnDownloadData(mvCustomerStockRecord obj, bool useTransaction) { return OnDownloadDataAsync(obj, useTransaction).Result; }
        protected override Exception OnUploadData(mvCustomerStockRecord obj, bool useTransaction) { return OnUploadDataAsync(obj, useTransaction).Result; }


        protected override async Task<Exception> OnDownloadAllDataAsync(bool continueOnError)
        {
            Exception exception = null;

            var customerStockRecordTableProvider = DbContext.GetDataTableProvider<mvCustomerStockRecordTableProvider>();
            var customerStockRecordServiceProvider = DataServiceContext.GetDataServiceProvider<mvCustomerStockRecordServiceProvider>();

            DateTime? syncDate = null;

            List<mvCustomerStockRecord> serverDataList = null;

            var minSyncDate = (DateTimeOffset?)await customerStockRecordTableProvider.GetData().MinAsync(p => p.SyncDate);

            for (int i = 0; i < DbContext.SyncMaxAttempts; i++)
            {
                try
                {
                    if (!syncDate.HasValue) syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();

                    var query = customerStockRecordServiceProvider.GetData().AddQueryOption("$select", Selector).Where(await GetFilter());

                    if (minSyncDate.HasValue)
                        query = query.Where(p => (p.CreatedDate > minSyncDate.Value));
                        
                    serverDataList = query.ToList();
                    break;
                }
                catch (Exception ex)
                {
                    if (i == (DbContext.SyncMaxAttempts - 1)) exception = ex;
                    else await Task.Delay(DbContext.SyncAttemptDelay);
                }
            }

            if (serverDataList != null)
            {
                int index = 0;
                foreach (var serverData in serverDataList)
                {
                    try
                    {
                        await ProcessLocalData(syncDate, 1, 1, serverData, null, customerStockRecordTableProvider, true);
                    }
                    catch (Exception ex)
                    {
                        if (!continueOnError)
                        {
                            exception = ex;
                            break;
                        }
                    }

                    index++;
                }
                
                await DbContext.UpdateAllSyncDateAsync<mvCustomerStockRecord>(syncDate.Value);
            }

            return exception;
        }
        
        protected override async Task<Exception> OnUploadAllDataAsync(bool continueOnError)
        {
            Exception exception = null;

            var customerStockRecordTableProvider = DbContext.GetDataTableProvider<mvCustomerStockRecordTableProvider>();
            var customerStockRecordServiceProvider = DataServiceContext.GetDataServiceProvider<mvCustomerStockRecordServiceProvider>();

            DateTime? syncDate = null;

            var localDataList = await customerStockRecordTableProvider.GetData().Where(p => (p.SyncDate == null)).ToListAsync();

            int index = 0;
            foreach (var obj in localDataList)
            {
                var lastStatus = 1;
                var serverData = new mvCustomerStockRecord();
                serverData.CopyFrom(obj);

                for (int i = 0; i < DbContext.SyncMaxAttempts; i++)
                {
                    try
                    {
                        if (!syncDate.HasValue) syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();

                        await customerStockRecordServiceProvider.InsertDataAsync(serverData, true);
                        
                        syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();
                        await ProcessLocalData(syncDate, 1, (i + 1), serverData, obj, customerStockRecordTableProvider, true);
                        break;
                    }
                    catch (Exception ex)
                    {
                        if (i == (DbContext.SyncMaxAttempts - 1))
                        {
                            exception = ex;
                            lastStatus = 0;
                            try { await ProcessLocalData(syncDate, 0, (i + 1), serverData, obj, customerStockRecordTableProvider, true); } catch (Exception) { }
                        }
                        else
                            await Task.Delay(DbContext.SyncAttemptDelay);
                    }
                }

                if ((lastStatus != 1) && !continueOnError)
                    break;

                index++;
            }

            return exception;
        }


        protected override async Task<Exception> OnDownloadDataAsync(mvCustomerStockRecord obj, bool useTransaction)
        {
            Exception exception = null;

            var customerStockRecordTableProvider = DbContext.GetDataTableProvider<mvCustomerStockRecordTableProvider>();
            var customerStockRecordServiceProvider = DataServiceContext.GetDataServiceProvider<mvCustomerStockRecordServiceProvider>();

            DateTime? syncDate = null;
            int status = 1;
            int attempts = 0;

            mvCustomerStockRecord serverData = null;

            for (int i = 0; i < DbContext.SyncMaxAttempts; i++)
            {
                try
                {
                    if (!syncDate.HasValue) syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();

                    serverData = customerStockRecordServiceProvider.GetData().AddQueryOption("$select", Selector)
                        .Where(p => p.CustomerID.Equals(serverData.CustomerID) && p.RecordDateID.Equals(serverData.RecordDateID) && p.ProductID.Equals(serverData.ProductID)).SingleOrDefault();
                    break;
                }
                catch (Exception ex)
                {
                    if (i == (DbContext.SyncMaxAttempts - 1)) { exception = ex; status = 0; }
                    else await Task.Delay(DbContext.SyncAttemptDelay);
                }
            }

            await ProcessLocalData(syncDate, status, attempts, serverData, obj, customerStockRecordTableProvider, useTransaction);

            return exception;
        }

        protected override async Task<Exception> OnUploadDataAsync(mvCustomerStockRecord obj, bool useTransaction)
        {
            Exception exception = null;

            var customerStockRecordTableProvider = DbContext.GetDataTableProvider<mvCustomerStockRecordTableProvider>();
            var customerStockRecordServiceProvider = DataServiceContext.GetDataServiceProvider<mvCustomerStockRecordServiceProvider>();

            DateTime? syncDate = null;
            int status = 1;
            int attempts = 0;

            var serverData = new mvCustomerStockRecord();
            serverData.CopyFrom(obj);

            for (int i = 0; i < DbContext.SyncMaxAttempts; i++)
            {
                try
                {
                    if (!syncDate.HasValue) syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();
                    attempts++;

                    await customerStockRecordServiceProvider.InsertDataAsync(serverData, useTransaction);
                    
                    syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();
                    break;
                }
                catch (Exception ex)
                {
                    if (i == (DbContext.SyncMaxAttempts - 1)) { exception = ex; status = 0; }
                    else await Task.Delay(DbContext.SyncAttemptDelay);
                }
            }

            await ProcessLocalData(syncDate, status, attempts, serverData, obj, customerStockRecordTableProvider, useTransaction);

            return exception;
        }



        private async Task ProcessLocalData(DateTime? syncDate, int status, int attempts, mvCustomerStockRecord serverData, mvCustomerStockRecord obj,
            mvCustomerStockRecordTableProvider tableProvider, bool useTransaction)
        {
            var localDate = (syncDate.HasValue) ? syncDate.Value : await DbContext.GetDatabaseUtcDateTimeAsync();
            mvCustomerStockRecord customerStockRecord = null;

            if (serverData == null)
            {
                customerStockRecord = new mvCustomerStockRecord();
                customerStockRecord.CustomerID = obj.CustomerID;
                customerStockRecord.RecordDateID = obj.RecordDateID;
                customerStockRecord.ProductID = obj.ProductID;

                await tableProvider.DeleteDataAsync(customerStockRecord, useTransaction);
            }
            else
            {
                var isInsert = false;
                customerStockRecord = await tableProvider.GetDataAsync(serverData.CustomerID, serverData.RecordDateID, serverData.ProductID);
                if (customerStockRecord == null)
                {
                    isInsert = true;
                    customerStockRecord = new mvCustomerStockRecord();
                }                

                customerStockRecord.CopyFrom(serverData);
                DbContext.SetSyncData(customerStockRecord, syncDate, localDate, status, attempts);

                if (isInsert)
                    await tableProvider.InsertDataAsync(customerStockRecord, useTransaction);
                else
                    await tableProvider.UpdateDataAsync(customerStockRecord, useTransaction);

                if (obj != null)
                {
                    obj.CopyFrom(serverData);
                    DbContext.CopySyncData(obj, customerStockRecord);
                }
            }
        }

        #endregion

    }

}
