// ===================================================================================
// Author        : System
// Created date  : 30 Aug 2020 07:11:04
// Description   : mvStockTransferDetailsEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using AIO.IDOS3.Data.Entity;
using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Mobile.Data.Entity
{

    public class mvStockTransferDetailsEntityTypeConfig : IEntityTypeConfiguration<mvStockTransferDetails>, IEdmEntityConfiguration<mvStockTransferDetails>
    {

        #region Fields

        private vStockTransferDetailsEntityTypeConfig parentConfig = new vStockTransferDetailsEntityTypeConfig();

        #endregion

        #region Implements IEntityTypeConfiguration<mvStockTransferDetails>

        public void Configure(EntityTypeBuilder<mvStockTransferDetails> builder)
        { 
            parentConfig.InternalConfigure(builder);

            builder.HasOne(p => p.Parent)
                .WithMany(q => q.ChildDetails)
                .HasForeignKey(p => new { p.DocumentID, p.ProductID })
                .OnDelete(DeleteBehavior.Cascade);
        }

        #endregion

        #region Implements IEdmEntityConfiguration<mvStockTransferDetails>

        public string EntitySetName { get { return parentConfig.EntitySetName; } }

        public void ConfigureEdmEntity(EntityTypeConfiguration<mvStockTransferDetails> builder) { parentConfig.InternalConfigureEdmEntity(builder); }

        #endregion

    }

}
