// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:46:40
// Description   : vUserRoleEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vUserRoleEntityTypeConfig : IEntityTypeConfiguration<vUserRole>, IEdmEntityConfiguration<vUserRole>
    {

        #region Implements IEntityTypeConfiguration<vUserRole>
        
        public void Configure(EntityTypeBuilder<vUserRole> builder) { InternalConfigure(builder); }

        #endregion
        
        #region Implements IEdmEntityConfiguration<vUserRole>

        public string EntitySetName { get; } = "vUserRoles";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vUserRole> builder) { InternalConfigureEdmEntity(builder); }

        #endregion
        
        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vUserRole
        {
            builder.ToTable("vUserRole");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.UserID, p.RoleID });
        }
        
        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vUserRole
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.UserID, p.RoleID });
        }

        #endregion

    }

}
