// ===================================================================================
// Author        : System
// Created date  : 30 Aug 2020 07:11:04
// Description   : mvInvoiceSummary class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using AIO.IDOS3.Data.Entity;

namespace AIO.IDOS3.Mobile.Data.Entity
{
    
    public partial class mvInvoiceSummary : vInvoiceSummary, ImvInvoiceSummary
    {

        #region Properties

        public new mvInvoice Parent { get; set; }

        #endregion

    }

}
