// ===================================================================================
// Author        : System
// Created date  : 08 Oct 2020 05:23:01
// Description   : mvExchangeRateSyncProvider partial class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Mobile.Data.Entity
{

    public partial class mvExchangeRateSyncProvider : DataSyncProvider<mvExchangeRate>
    {

        #region Properties
        
        public static string Selector = "ID,OriginCurrencyID,ExchangeCurrencyID,ValidDateFrom,ValidDateTo,Amount,StatusID,StatusName,CreatedDate,ModifiedDate,IsDeleted";
        
        #endregion
        
        #region Methods
        
        protected override Exception OnDownloadAllData(bool continueOnError) { return OnDownloadAllDataAsync(continueOnError).Result; }
        protected override Exception OnUploadAllData(bool continueOnError) { return OnUploadAllDataAsync(continueOnError).Result; }
        protected override Exception OnDownloadData(mvExchangeRate obj, bool useTransaction) { return OnDownloadDataAsync(obj, useTransaction).Result; }
        protected override Exception OnUploadData(mvExchangeRate obj, bool useTransaction) { return OnUploadDataAsync(obj, useTransaction).Result; }


        protected override async Task<Exception> OnDownloadAllDataAsync(bool continueOnError)
        {
            Exception exception = null;

            var exchangeRateTableProvider = DbContext.GetDataTableProvider<mvExchangeRateTableProvider>();
            var exchangeRateServiceProvider = DataServiceContext.GetDataServiceProvider<mvExchangeRateServiceProvider>();

            DateTime? syncDate = null;

            List<mvExchangeRate> serverDataList = null;

            var minSyncDate = (DateTimeOffset?)await exchangeRateTableProvider.GetData().MinAsync(p => p.SyncDate);

            for (int i = 0; i < DbContext.SyncMaxAttempts; i++)
            {
                try
                {
                    if (!syncDate.HasValue) syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();

                    var query = (IQueryable<mvExchangeRate>)exchangeRateServiceProvider.GetData().AddQueryOption("$select", Selector);

                    if (minSyncDate.HasValue)
                        query = query.Where(p => (p.CreatedDate > minSyncDate.Value) || ((p.ModifiedDate != null) && (p.ModifiedDate.Value > minSyncDate.Value)));
                        
                    serverDataList = query.ToList();
                    break;
                }
                catch (Exception ex)
                {
                    if (i == (DbContext.SyncMaxAttempts - 1)) exception = ex;
                    else await Task.Delay(DbContext.SyncAttemptDelay);
                }
            }

            if (serverDataList != null)
            {
                int index = 0;
                foreach (var serverData in serverDataList)
                {
                    try
                    {
                        await ProcessLocalData(syncDate, 1, 1, serverData, null, exchangeRateTableProvider, true);
                    }
                    catch (Exception ex)
                    {
                        if (!continueOnError)
                        {
                            exception = ex;
                            break;
                        }
                    }

                    index++;
                }
                
                await DbContext.UpdateAllSyncDateAsync<mvExchangeRate>(syncDate.Value);
            }

            return exception;
        }
        
        protected override async Task<Exception> OnUploadAllDataAsync(bool continueOnError)
        {
            Exception exception = new NotImplementedException();

            return await Task.FromResult(exception);
        }


        protected override async Task<Exception> OnDownloadDataAsync(mvExchangeRate obj, bool useTransaction)
        {
            Exception exception = null;

            var exchangeRateTableProvider = DbContext.GetDataTableProvider<mvExchangeRateTableProvider>();
            var exchangeRateServiceProvider = DataServiceContext.GetDataServiceProvider<mvExchangeRateServiceProvider>();

            DateTime? syncDate = null;
            int status = 1;
            int attempts = 0;

            mvExchangeRate serverData = null;

            for (int i = 0; i < DbContext.SyncMaxAttempts; i++)
            {
                try
                {
                    if (!syncDate.HasValue) syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();

                    serverData = exchangeRateServiceProvider.GetData().AddQueryOption("$select", Selector)
                        .Where(p => (p.ID == obj.ID)).SingleOrDefault();
                    break;
                }
                catch (Exception ex)
                {
                    if (i == (DbContext.SyncMaxAttempts - 1)) { exception = ex; status = 0; }
                    else await Task.Delay(DbContext.SyncAttemptDelay);
                }
            }

            await ProcessLocalData(syncDate, status, attempts, serverData, obj, exchangeRateTableProvider, useTransaction);

            return exception;
        }

        protected override async Task<Exception> OnUploadDataAsync(mvExchangeRate obj, bool useTransaction)
        {
            Exception exception = new NotImplementedException();

            return await Task.FromResult(exception);
        }



        private async Task ProcessLocalData(DateTime? syncDate, int status, int attempts, mvExchangeRate serverData, mvExchangeRate obj,
            mvExchangeRateTableProvider tableProvider, bool useTransaction)
        {
            var localDate = (syncDate.HasValue) ? syncDate.Value : await DbContext.GetDatabaseUtcDateTimeAsync();
            mvExchangeRate exchangeRate = null;

            if (serverData == null)
            {
                exchangeRate = new mvExchangeRate();
                exchangeRate.ID = obj.ID;

                await tableProvider.DeleteDataAsync(exchangeRate, useTransaction);
            }
            else
            {
                var isInsert = false;
                var isDelete = false;
                exchangeRate = await tableProvider.GetDataAsync(serverData.ID);
                if (exchangeRate == null)
                {
                    isInsert = true;
                    exchangeRate = new mvExchangeRate();
                }                
                else if (exchangeRate.IsDeleted)
                    isDelete = true;                    

                exchangeRate.CopyFrom(serverData);
                DbContext.SetSyncData(exchangeRate, syncDate, localDate, status, attempts);

                if (isInsert)
                    await tableProvider.InsertDataAsync(exchangeRate, useTransaction);
                else if (isDelete)
                    await tableProvider.DeleteDataAsync(exchangeRate, useTransaction);
                else
                    await tableProvider.UpdateDataAsync(exchangeRate, useTransaction);

                if (obj != null)
                {
                    obj.CopyFrom(serverData);
                    DbContext.CopySyncData(obj, exchangeRate);
                }
            }
        }

        #endregion

    }

}
