// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:46:08
// Description   : vProductPriceEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vProductPriceEntityTypeConfig : IEntityTypeConfiguration<vProductPrice>, IEdmEntityConfiguration<vProductPrice>
    {

        #region Implements IEntityTypeConfiguration<vProductPrice>
        
        public void Configure(EntityTypeBuilder<vProductPrice> builder) { InternalConfigure(builder); }

        #endregion
        
        #region Implements IEdmEntityConfiguration<vProductPrice>

        public string EntitySetName { get; } = "vProductPrices";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vProductPrice> builder) { InternalConfigureEdmEntity(builder); }

        #endregion
        
        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vProductPrice
        {
            builder.ToTable("vProductPrice");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.ID });
        }
        
        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vProductPrice
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.ID });
        }

        #endregion

    }

}
