// ===================================================================================
// Author        : System
// Created date  : 06 Aug 2020 17:31:01
// Description   : CashDepositReceiptDetailsEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AIO.IDOS3.Data.Entity
{

    public class CashDepositReceiptDetailsEntityTypeConfig : IEntityTypeConfiguration<CashDepositReceiptDetails>
    {

        #region Implements IEntityTypeConfiguration<CashDepositReceiptDetails>
        
        public void Configure(EntityTypeBuilder<CashDepositReceiptDetails> builder) { InternalConfigure(builder); }

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : CashDepositReceiptDetails
        {
            builder.ToTable("CashDepositReceiptDetails");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.DocumentID, p.CollectorID, p.PRDocumentID });
        }
        
        #endregion

    }

}
