// ===================================================================================
// Author        : System
// Created date  : 24 Sep 2020 03:19:46
// Description   : SalesPromotionEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AIO.IDOS3.Data.Entity
{

    public class SalesPromotionEntityTypeConfig : IEntityTypeConfiguration<SalesPromotion>
    {

        #region Implements IEntityTypeConfiguration<SalesPromotion>
        
        public void Configure(EntityTypeBuilder<SalesPromotion> builder)
        {
            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.ID });
            builder.Property(p => p.ID).ValueGeneratedOnAdd();
        }
        
        #endregion

    }

}
