// ===================================================================================
// Author        : System
// Created date  : 25 Sep 2020 00:13:26
// Description   : mvSalesCallEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using AIO.IDOS3.Data.Entity;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Mobile.Data.Entity
{

    public class mvSalesCallEntityTypeConfig : IEntityTypeConfiguration<mvSalesCall>, IEdmEntityConfiguration<mvSalesCall>
    {

        #region Fields

        private vSalesCallEntityTypeConfig parentConfig = new vSalesCallEntityTypeConfig();

        #endregion

        #region Implements IEntityTypeConfiguration<mvSalesCall>

        public void Configure(EntityTypeBuilder<mvSalesCall> builder)
        {
            parentConfig.InternalConfigure(builder);

            builder.HasOne(p => p.ParentActivity)
                .WithMany(q => q.ChildSalesCalls)
                .HasForeignKey(p => p.ActivityID)
                .OnDelete(DeleteBehavior.Cascade);
        }

        #endregion

        #region Implements IEdmEntityConfiguration<mvSalesCall>

        public string EntitySetName { get { return parentConfig.EntitySetName; } }

        public void ConfigureEdmEntity(EntityTypeConfiguration<mvSalesCall> builder) { parentConfig.InternalConfigureEdmEntity(builder); }

        #endregion

    }

}
