// ===================================================================================
// Author        : System
// Created date  : 25 Sep 2020 00:18:58
// Description   : SalesCallEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AIO.IDOS3.Data.Entity
{

    public class SalesCallEntityTypeConfig : IEntityTypeConfiguration<SalesCall>
    {

        #region Implements IEntityTypeConfiguration<SalesCall>
                
        public void Configure(EntityTypeBuilder<SalesCall> builder) { InternalConfigure(builder); }
        
        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : SalesCall
        {
            builder.ToTable("SalesCall");
            
            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.ID });
        }
        
        #endregion

    }

}
