// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:46:13
// Description   : vSalesOrderFOCDetailsEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vSalesOrderFOCDetailsEntityTypeConfig : IEntityTypeConfiguration<vSalesOrderFOCDetails>, IEdmEntityConfiguration<vSalesOrderFOCDetails>
    {

        #region Implements IEntityTypeConfiguration<vSalesOrderFOCDetails>

        public void Configure(EntityTypeBuilder<vSalesOrderFOCDetails> builder)
        {
            InternalConfigure(builder);

            builder.HasOne(p => p.Parent)
                .WithMany(q => q.ChildDetails)
                .HasForeignKey(p => new { p.DocumentID, p.ProductID })
                .OnDelete(DeleteBehavior.Cascade);
        }

        #endregion

        #region Implements IEdmEntityConfiguration<vSalesOrderFOCDetails>

        public string EntitySetName { get; } = "vSalesOrderFOCDetails";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vSalesOrderFOCDetails> builder) { InternalConfigureEdmEntity(builder); }

        #endregion

        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vSalesOrderFOCDetails
        {
            builder.ToTable("vSalesOrderFOCDetails");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.DocumentID, p.ProductID, p.ProductLotID });
        }

        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vSalesOrderFOCDetails
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.DocumentID, p.ProductID, p.ProductLotID });
        }

        #endregion

    }

}
