// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:45:05
// Description   : InvoiceEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AIO.IDOS3.Data.Entity
{

    public class InvoiceEntityTypeConfig : IEntityTypeConfiguration<Invoice>
    {

        #region Implements IEntityTypeConfiguration<Invoice>
        
        public void Configure(EntityTypeBuilder<Invoice> builder) { InternalConfigure(builder); }

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : Invoice
        {
            builder.ToTable("Invoice");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.DocumentID });
        }
        
        #endregion

    }

}
