// ===================================================================================
// Author        : System
// Created date  : 09 Aug 2020 16:32:39
// Description   : UserPermissionTableProvider partial class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using System.Threading.Tasks;
using Wismapi.Data;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public partial class UserPermissionTableProvider : DataTableProvider<UserPermission>
    {
        
        #region Methods

        protected override async Task OnBeginInsertDataAsync(BeginOperationDataEventArgs<UserPermission> e)
        {
            e.Data.CreatedDate = await DbContext.GetDatabaseUtcDateTimeAsync();

            var authenticatedUser = ((MainDbContext)DbContext).GetAuthenticatedUser();
            if (authenticatedUser != null)
                e.Data.CreatedByUserID = authenticatedUser.ID;

            await base.OnBeginInsertDataAsync(e);
        }

        protected override async Task OnBeginUpdateDataAsync(BeginOperationDataEventArgs<UserPermission> e)
        {
            await Task.CompletedTask;
            await base.OnBeginUpdateDataAsync(e);
        }

        protected override async Task OnBeginDeleteDataAsync(BeginOperationDataEventArgs<UserPermission> e)
        {
            await Task.CompletedTask;
            await base.OnBeginDeleteDataAsync(e);
        }

        #endregion
        
    }

}
