// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:46:12
// Description   : vSalesmanProductTargetEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vSalesmanProductTargetEntityTypeConfig : IEntityTypeConfiguration<vSalesmanProductTarget>, IEdmEntityConfiguration<vSalesmanProductTarget>
    {

        #region Implements IEntityTypeConfiguration<vSalesmanProductTarget>
        
        public void Configure(EntityTypeBuilder<vSalesmanProductTarget> builder) { InternalConfigure(builder); }

        #endregion
        
        #region Implements IEdmEntityConfiguration<vSalesmanProductTarget>

        public string EntitySetName { get; } = "vSalesmanProductTargets";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vSalesmanProductTarget> builder) { InternalConfigureEdmEntity(builder); }

        #endregion
        
        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vSalesmanProductTarget
        {
            builder.ToTable("vSalesmanProductTarget");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.SalesmanID, p.PeriodID, p.ProductID });
        }
        
        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vSalesmanProductTarget
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.SalesmanID, p.PeriodID, p.ProductID });
        }

        #endregion

    }

}
