// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:46:18
// Description   : vSiteEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vSiteEntityTypeConfig : IEntityTypeConfiguration<vSite>, IEdmEntityConfiguration<vSite>
    {

        #region Implements IEntityTypeConfiguration<vSite>
        
        public void Configure(EntityTypeBuilder<vSite> builder) { InternalConfigure(builder); }

        #endregion
        
        #region Implements IEdmEntityConfiguration<vSite>

        public string EntitySetName { get; } = "vSites";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vSite> builder) { InternalConfigureEdmEntity(builder); }

        #endregion
        
        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vSite
        {
            builder.ToTable("vSite");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.ID });
        }
        
        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vSite
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.ID });
        }

        #endregion

    }

}
