// ===================================================================================
// Author        : System
// Created date  : 09 Aug 2020 15:54:51
// Description   : vUserPermissionViewProvider partial class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using System;
using System.Threading.Tasks;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public partial class vUserPermissionViewProvider : DataViewProvider<vUserPermission>
    {

        #region Methods
        
        protected override void OnInsertData(vUserPermission obj, bool useTransaction) { OnInsertDataAsync(obj, useTransaction).Wait(); }
        protected override void OnUpdateData(vUserPermission obj, bool useTransaction) { OnUpdateDataAsync(obj, useTransaction).Wait(); }
        protected override void OnDeleteData(vUserPermission obj, bool useTransaction) { OnDeleteDataAsync(obj, useTransaction).Wait(); }


        protected override async Task OnInsertDataAsync(vUserPermission obj, bool useTransaction)
        {
            var userPermissionTableProvider = DbContext.GetDataTableProvider<UserPermissionTableProvider>();

            var userPermission = new UserPermission();

            userPermission.UserID = obj.UserID;
            userPermission.PermissionObjectID = obj.PermissionObjectID;

            await userPermissionTableProvider.InsertDataAsync(userPermission);
        }

        protected override async Task OnUpdateDataAsync(vUserPermission obj, bool useTransaction)
        {
            var userPermissionTableProvider = DbContext.GetDataTableProvider<UserPermissionTableProvider>();

            var userPermission = await userPermissionTableProvider.GetDataAsync(obj.UserID, obj.PermissionObjectID);


            await userPermissionTableProvider.UpdateDataAsync(userPermission);
        }

        protected override async Task OnDeleteDataAsync(vUserPermission obj, bool useTransaction)
        {
            await Task.CompletedTask;
            throw new NotImplementedException();
        }

        #endregion

    }

}
