// ===================================================================================
// Author        : System
// Created date  : 30 Aug 2020 07:11:04
// Description   : vUserPermission class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.OData.Client;
using System.Collections.ObjectModel;

namespace AIO.IDOS3.Data.Entity
{

    [Key("UserID", "PermissionObjectID")]
    public partial class vUserPermission : BaseEntityType, IvUserPermission
    {

        #region Properties

        public vUser ParentUser { get; set; }

        #endregion

    }

}
