// ===================================================================================
// Author        : System
// Created date  : 30 Aug 2020 07:11:04
// Description   : mvStockTransferEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using AIO.IDOS3.Data.Entity;
using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Mobile.Data.Entity
{

    public class mvStockTransferEntityTypeConfig : IEntityTypeConfiguration<mvStockTransfer>, IEdmEntityConfiguration<mvStockTransfer>
    {

        #region Fields

        private vStockTransferEntityTypeConfig parentConfig = new vStockTransferEntityTypeConfig();

        #endregion

        #region Implements IEntityTypeConfiguration<mvStockTransfer>

        public void Configure(EntityTypeBuilder<mvStockTransfer> builder) { parentConfig.InternalConfigure(builder); }

        #endregion

        #region Implements IEdmEntityConfiguration<mvStockTransfer>

        public string EntitySetName { get { return parentConfig.EntitySetName; } }

        public void ConfigureEdmEntity(EntityTypeConfiguration<mvStockTransfer> builder) { parentConfig.InternalConfigureEdmEntity(builder); }

        #endregion

    }

}
