// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:46:27
// Description   : vStockOnHandCurrentEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vStockOnHandCurrentEntityTypeConfig : IEntityTypeConfiguration<vStockOnHandCurrent>, IEdmEntityConfiguration<vStockOnHandCurrent>
    {

        #region Implements IEntityTypeConfiguration<vStockOnHandCurrent>

        public void Configure(EntityTypeBuilder<vStockOnHandCurrent> builder) { InternalConfigure(builder); }

        #endregion

        #region Implements IEdmEntityConfiguration<vStockOnHandCurrent>

        public string EntitySetName { get; } = "vStockOnHandCurrents";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vStockOnHandCurrent> builder) { InternalConfigureEdmEntity(builder); }

        #endregion

        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vStockOnHandCurrent
        {
            builder.ToTable("vStockOnHandCurrent");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.ID });
        }

        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vStockOnHandCurrent
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.ID });
        }

        #endregion

    }

}
