// ===================================================================================
// Author        : System
// Created date  : 30 Aug 2020 07:11:04
// Description   : mvSalesOrderReturnEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using AIO.IDOS3.Data.Entity;
using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Mobile.Data.Entity
{

    public class mvSalesOrderReturnEntityTypeConfig : IEntityTypeConfiguration<mvSalesOrderReturn>, IEdmEntityConfiguration<mvSalesOrderReturn>
    {

        #region Fields

        private vSalesOrderReturnEntityTypeConfig parentConfig = new vSalesOrderReturnEntityTypeConfig();

        #endregion

        #region Implements IEntityTypeConfiguration<mvSalesOrderReturn>

        public void Configure(EntityTypeBuilder<mvSalesOrderReturn> builder) { parentConfig.InternalConfigure(builder); }

        #endregion

        #region Implements IEdmEntityConfiguration<mvSalesOrderReturn>

        public string EntitySetName { get { return parentConfig.EntitySetName; } }

        public void ConfigureEdmEntity(EntityTypeConfiguration<mvSalesOrderReturn> builder) { parentConfig.InternalConfigureEdmEntity(builder); }

        #endregion

    }

}
