// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:46:09
// Description   : vRoleAuthorizationEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vRoleAuthorizationEntityTypeConfig : IEntityTypeConfiguration<vRoleAuthorization>, IEdmEntityConfiguration<vRoleAuthorization>
    {

        #region Implements IEntityTypeConfiguration<vRoleAuthorization>
        
        public void Configure(EntityTypeBuilder<vRoleAuthorization> builder) { InternalConfigure(builder); }

        #endregion
        
        #region Implements IEdmEntityConfiguration<vRoleAuthorization>

        public string EntitySetName { get; } = "vRoleAuthorizations";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vRoleAuthorization> builder) { InternalConfigureEdmEntity(builder); }

        #endregion
        
        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vRoleAuthorization
        {
            builder.ToTable("vRoleAuthorization");

            //// Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.RoleID, p.PermissionObjectID });
        }
        
        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vRoleAuthorization
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.RoleID, p.PermissionObjectID });
        }

        #endregion

    }

}
