// ===================================================================================
// Author        : System
// Created date  : 15 Sep 2020 03:27:00
// Description   : mvSalesOrderReturnDetailsEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using AIO.IDOS3.Data.Entity;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Mobile.Data.Entity
{

    public class mvSalesOrderReturnDetailsEntityTypeConfig : IEntityTypeConfiguration<mvSalesOrderReturnDetails>, IEdmEntityConfiguration<mvSalesOrderReturnDetails>
    {

        #region Fields

        private vSalesOrderReturnDetailsEntityTypeConfig parentConfig = new vSalesOrderReturnDetailsEntityTypeConfig();

        #endregion

        #region Implements IEntityTypeConfiguration<mvSalesOrderReturnDetails>

        public void Configure(EntityTypeBuilder<mvSalesOrderReturnDetails> builder) { parentConfig.InternalConfigure(builder); }

        #endregion

        #region Implements IEdmEntityConfiguration<mvSalesOrderReturnDetails>

        public string EntitySetName { get { return parentConfig.EntitySetName; } }

        public void ConfigureEdmEntity(EntityTypeConfiguration<mvSalesOrderReturnDetails> builder) { parentConfig.InternalConfigureEdmEntity(builder); }

        #endregion

    }

}
