// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:45:53
// Description   : vCompanyAddressEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vCompanyAddressEntityTypeConfig : IEntityTypeConfiguration<vCompanyAddress>, IEdmEntityConfiguration<vCompanyAddress>
    {

        #region Implements IEntityTypeConfiguration<vCompanyAddress>
        
        public void Configure(EntityTypeBuilder<vCompanyAddress> builder) { InternalConfigure(builder); }

        #endregion
        
        #region Implements IEdmEntityConfiguration<vCompanyAddress>

        public string EntitySetName { get; } = "vCompanyAddresses";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vCompanyAddress> builder) { InternalConfigureEdmEntity(builder); }

        #endregion
        
        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vCompanyAddress
        {
            builder.ToTable("vCompanyAddress");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.CompanyID });
        }
        
        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vCompanyAddress
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.CompanyID });
        }

        #endregion

    }

}
