// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:45:57
// Description   : vDeliveryEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vDeliveryEntityTypeConfig : IEntityTypeConfiguration<vDelivery>, IEdmEntityConfiguration<vDelivery>
    {

        #region Implements IEntityTypeConfiguration<vDelivery>
        
        public void Configure(EntityTypeBuilder<vDelivery> builder) { InternalConfigure(builder); }

        #endregion
        
        #region Implements IEdmEntityConfiguration<vDelivery>

        public string EntitySetName { get; } = "vDeliveries";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vDelivery> builder) { InternalConfigureEdmEntity(builder); }

        #endregion
        
        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vDelivery
        {
            builder.ToTable("vDelivery");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.ID });
        }
        
        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vDelivery
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.ID });
        }

        #endregion

    }

}
