// ===================================================================================
// Author        : System
// Created date  : 30 Aug 2020 07:11:01
// Description   : mvCustomerEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using AIO.IDOS3.Data.Entity;
using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Mobile.Data.Entity
{

    public class mvCustomerEntityTypeConfig : IEntityTypeConfiguration<mvCustomer>, IEdmEntityConfiguration<mvCustomer>
    {

        #region Fields

        private vCustomerEntityTypeConfig parentConfig = new vCustomerEntityTypeConfig();

        #endregion

        #region Implements IEntityTypeConfiguration<mvCustomer>

        public void Configure(EntityTypeBuilder<mvCustomer> builder) { parentConfig.InternalConfigure(builder); }

        #endregion

        #region Implements IEdmEntityConfiguration<mvCustomer>

        public string EntitySetName { get { return parentConfig.EntitySetName; } }

        public void ConfigureEdmEntity(EntityTypeConfiguration<mvCustomer> builder) { parentConfig.InternalConfigureEdmEntity(builder); }

        #endregion

    }

}
