// ===================================================================================
// Author        : System
// Created date  : 17 Aug 2020 01:45:40
// Description   : vUserNotificationController class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using AIO.IDOS3.Data;
using AIO.IDOS3.Data.Entity;
using Microsoft.AspNet.OData;
using Microsoft.AspNet.OData.Query;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace AIO.IDOS3.Web.Services.Controllers.DataServices
{

    public class vUserNotificationsController : DataServiceController<vUserNotification>
    {

        #region Constructors
                
        public vUserNotificationsController(ILogger<vUserNotificationsController> logger, MainDbContext context)
            : base(logger, context)
        {

        }

        #endregion

        #region Methods

        [EnableQuery]
        [HttpGet]
        public IQueryable<vUserNotification> Get()
        {
            var viewProvider = context.GetDataViewProvider<vUserNotificationViewProvider>();

            return viewProvider.GetData();
        }
        
        [EnableQuery]
        [HttpGet]
        public async Task<IActionResult> Get([FromODataUri] Guid keyID)
        {
            var viewProvider = context.GetDataViewProvider<vUserNotificationViewProvider>();

            return Ok(await viewProvider.GetDataAsync(keyID));
        }



        [HttpPost]
        public async Task<IActionResult> Post([FromBody] vUserNotification obj)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);

            var viewProvider = context.GetDataViewProvider<vUserNotificationViewProvider>();

            using (var transaction = await context.Database.BeginTransactionAsync())
            {
                try
                {
                    await viewProvider.InsertDataAsync(obj, true);
                    await transaction.CommitAsync();
                }
                catch (Exception ex)
                {
                    await transaction.RollbackAsync();
                    throw ex;
                }
            }

            return Created(obj);
        }
        
        [HttpPatch]
        public async Task<IActionResult> Patch([FromODataUri] Guid keyID, [FromBody] vUserNotification obj)
        {
            return await Put(keyID, obj);
        }
        
        [HttpPut]
        public async Task<IActionResult> Put([FromODataUri] Guid keyID, [FromBody] vUserNotification obj)
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);

            var viewProvider = context.GetDataViewProvider<vUserNotificationViewProvider>();

            obj.ID = keyID;
			
            using (var transaction = await context.Database.BeginTransactionAsync())
            {
                try
                {
                    await viewProvider.UpdateDataAsync(obj, true);
                    await transaction.CommitAsync();
                }
                catch (Exception ex)
                {
                    await transaction.RollbackAsync();
                    throw ex;
                }
            }

            return Updated(obj);
        }

        [HttpDelete]
        public async Task<IActionResult> Delete([FromODataUri] Guid keyID)
        {
            var viewProvider = context.GetDataViewProvider<vUserNotificationViewProvider>();

            var obj = new vUserNotification();
            obj.ID = keyID;
			
            using (var transaction = await context.Database.BeginTransactionAsync())
            {
                try
                {
                    await viewProvider.DeleteDataAsync(obj, true);
                    await transaction.CommitAsync();
                }
                catch (Exception ex)
                {
                    await transaction.RollbackAsync();
                    throw ex;
                }
            }

            return StatusCode((int)HttpStatusCode.NoContent);
        }

        #endregion

    }

}
