// ===================================================================================
// Author        : System
// Created date  : 08 Oct 2020 05:23:02
// Description   : mvGiroSyncProvider partial class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Mobile.Data.Entity
{

    public partial class mvGiroSyncProvider : DataSyncProvider<mvGiro>
    {

        #region Properties
        
        public static string Selector = "ID,BankID,Code,BankCode,BankName,Bank,Giro,CurrentAccountCode,CurrentAccountName,ReceivedDate,IssuedDate,IsIssuedByCustomer,IssuedByCustomerBillGroupID,IssuedByCustomerBillGroupCode,IssuedByCustomerBillGroupName,IssuedByCustomerBillGroup,IssuedByCustomerBillGroupHeadID,IssuedByCustomerBillGroupHeadCode,IssuedByCustomerBillGroupHeadName,IssuedByCustomerBillGroupHead,IssuedByCustomerID,IssuedByCustomerCode,IssuedByCustomerName,IssuedByCustomer,CollectorID,CollectorCode,CollectorName,Collector,IsCollectedByHeadOffice,CollectedBySiteID,CollectedBySiteCode,CollectedBySiteName,CollectedBySite,CollectedByAreaID,CollectedByAreaCode,CollectedByAreaName,CollectedByArea,CollectedByRegionID,CollectedByRegionCode,CollectedByRegionName,CollectedByRegion,CollectedByTerritoryID,CollectedByTerritoryCode,CollectedByTerritoryName,CollectedByTerritory,CollectedByCompanyID,CollectedByCompanyCode,CollectedByCompanyName,CollectedByCompany,CollectedBySiteDistributionTypeID,CollectedBySiteDistributionTypeName,IsCollectedBySiteProductLotCodeEntryRequired,IsCheque,EffectiveDateFrom,EffectiveDateTo,Amount,IncomingAccountID,IncomingAccountCode,IncomingAccountName,IncomingAccount,IncomingBankID,IncomingBankCode,IncomingBankName,IncomingBank,Remarks,PCDocumentID,PCDocumentCode,PCTransactionDate,StatusID,StatusName,ClearingDate,Photo,CreatedDate,CreatedByUserID,CreatedByUserName,ModifiedDate,ModifiedByUserID,ModifiedByUserName,IsDeleted";
        
        #endregion
        
        #region Methods
        
        private async Task<Expression<Func<mvGiro, bool>>> GetFilter()
        {
            await Task.CompletedTask;
            throw new NotImplementedException();
        }
        
        
        
        protected override Exception OnDownloadAllData(bool continueOnError) { return OnDownloadAllDataAsync(continueOnError).Result; }
        protected override Exception OnUploadAllData(bool continueOnError) { return OnUploadAllDataAsync(continueOnError).Result; }
        protected override Exception OnDownloadData(mvGiro obj, bool useTransaction) { return OnDownloadDataAsync(obj, useTransaction).Result; }
        protected override Exception OnUploadData(mvGiro obj, bool useTransaction) { return OnUploadDataAsync(obj, useTransaction).Result; }


        protected override async Task<Exception> OnDownloadAllDataAsync(bool continueOnError)
        {
            Exception exception = null;

            var giroTableProvider = DbContext.GetDataTableProvider<mvGiroTableProvider>();
            var giroServiceProvider = DataServiceContext.GetDataServiceProvider<mvGiroServiceProvider>();

            DateTime? syncDate = null;

            List<mvGiro> serverDataList = null;

            var minSyncDate = (DateTimeOffset?)await giroTableProvider.GetData().MinAsync(p => p.SyncDate);

            for (int i = 0; i < DbContext.SyncMaxAttempts; i++)
            {
                try
                {
                    if (!syncDate.HasValue) syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();

                    var query = giroServiceProvider.GetData().AddQueryOption("$select", Selector).Where(await GetFilter());

                    if (minSyncDate.HasValue)
                        query = query.Where(p => (p.CreatedDate > minSyncDate.Value) || ((p.ModifiedDate != null) && (p.ModifiedDate.Value > minSyncDate.Value)));
                        
                    serverDataList = query.ToList();
                    break;
                }
                catch (Exception ex)
                {
                    if (i == (DbContext.SyncMaxAttempts - 1)) exception = ex;
                    else await Task.Delay(DbContext.SyncAttemptDelay);
                }
            }

            if (serverDataList != null)
            {
                int index = 0;
                foreach (var serverData in serverDataList)
                {
                    try
                    {
                        await ProcessLocalData(syncDate, 1, 1, serverData, null, giroTableProvider, true);
                    }
                    catch (Exception ex)
                    {
                        if (!continueOnError)
                        {
                            exception = ex;
                            break;
                        }
                    }

                    index++;
                }
                
                await DbContext.UpdateAllSyncDateAsync<mvGiro>(syncDate.Value);
            }

            return exception;
        }
        
        protected override async Task<Exception> OnUploadAllDataAsync(bool continueOnError)
        {
            Exception exception = null;

            var giroTableProvider = DbContext.GetDataTableProvider<mvGiroTableProvider>();
            var giroServiceProvider = DataServiceContext.GetDataServiceProvider<mvGiroServiceProvider>();

            DateTime? syncDate = null;

            var localDataList = await giroTableProvider.GetData().Where(p => (p.SyncDate == null) && !p.IsDeleted).ToListAsync();

            int index = 0;
            foreach (var obj in localDataList)
            {
                var lastStatus = 1;
                var serverData = new mvGiro();
                serverData.CopyFrom(obj);

                if (serverData.SyncDate == null)
                    serverData.PCDocumentID = null;

                for (int i = 0; i < DbContext.SyncMaxAttempts; i++)
                {
                    try
                    {
                        if (!syncDate.HasValue) syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();

                        await giroServiceProvider.InsertDataAsync(serverData, true);
                        
                        syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();
                        await ProcessLocalData(syncDate, 1, (i + 1), serverData, obj, giroTableProvider, true);
                        break;
                    }
                    catch (Exception ex)
                    {
                        if (i == (DbContext.SyncMaxAttempts - 1))
                        {
                            exception = ex;
                            lastStatus = 0;
                            try { await ProcessLocalData(syncDate, 0, (i + 1), serverData, obj, giroTableProvider, true); } catch (Exception) { }
                        }
                        else
                            await Task.Delay(DbContext.SyncAttemptDelay);
                    }
                }

                if ((lastStatus != 1) && !continueOnError)
                    break;

                index++;
            }

            return exception;
        }


        protected override async Task<Exception> OnDownloadDataAsync(mvGiro obj, bool useTransaction)
        {
            Exception exception = null;

            var giroTableProvider = DbContext.GetDataTableProvider<mvGiroTableProvider>();
            var giroServiceProvider = DataServiceContext.GetDataServiceProvider<mvGiroServiceProvider>();

            DateTime? syncDate = null;
            int status = 1;
            int attempts = 0;

            mvGiro serverData = null;

            for (int i = 0; i < DbContext.SyncMaxAttempts; i++)
            {
                try
                {
                    if (!syncDate.HasValue) syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();

                    serverData = giroServiceProvider.GetData().AddQueryOption("$select", Selector)
                        .Where(p => p.ID.Equals(obj.ID)).SingleOrDefault();
                    break;
                }
                catch (Exception ex)
                {
                    if (i == (DbContext.SyncMaxAttempts - 1)) { exception = ex; status = 0; }
                    else await Task.Delay(DbContext.SyncAttemptDelay);
                }
            }

            await ProcessLocalData(syncDate, status, attempts, serverData, obj, giroTableProvider, useTransaction);

            return exception;
        }

        protected override async Task<Exception> OnUploadDataAsync(mvGiro obj, bool useTransaction)
        {
            Exception exception = null;

            var giroTableProvider = DbContext.GetDataTableProvider<mvGiroTableProvider>();
            var giroServiceProvider = DataServiceContext.GetDataServiceProvider<mvGiroServiceProvider>();

            DateTime? syncDate = null;
            int status = 1;
            int attempts = 0;

            var serverData = new mvGiro();
            serverData.CopyFrom(obj);

            if (serverData.SyncDate == null)
                serverData.PCDocumentID = null;

            for (int i = 0; i < DbContext.SyncMaxAttempts; i++)
            {
                try
                {
                    if (!syncDate.HasValue) syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();
                    attempts++;

                    await giroServiceProvider.InsertDataAsync(serverData, useTransaction);
                    
                    syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();
                    break;
                }
                catch (Exception ex)
                {
                    if (i == (DbContext.SyncMaxAttempts - 1)) { exception = ex; status = 0; }
                    else await Task.Delay(DbContext.SyncAttemptDelay);
                }
            }

            await ProcessLocalData(syncDate, status, attempts, serverData, obj, giroTableProvider, useTransaction);

            return exception;
        }



        private async Task ProcessLocalData(DateTime? syncDate, int status, int attempts, mvGiro serverData, mvGiro obj,
            mvGiroTableProvider tableProvider, bool useTransaction)
        {
            var localDate = (syncDate.HasValue) ? syncDate.Value : await DbContext.GetDatabaseUtcDateTimeAsync();
            mvGiro giro = null;

            if (serverData == null)
            {
                giro = new mvGiro();
                giro.ID = obj.ID;

                await tableProvider.DeleteDataAsync(giro, useTransaction);
            }
            else
            {
                var isInsert = false;
                var isDelete = false;
                giro = await tableProvider.GetDataAsync(serverData.ID);
                if (giro == null)
                {
                    isInsert = true;
                    giro = new mvGiro();
                }                
                else if (giro.IsDeleted)
                    isDelete = true;                    

                giro.CopyFrom(serverData);
                DbContext.SetSyncData(giro, syncDate, localDate, status, attempts);

                if (isInsert)
                    await tableProvider.InsertDataAsync(giro, useTransaction);
                else if (isDelete)
                    await tableProvider.DeleteDataAsync(giro, useTransaction);
                else
                    await tableProvider.UpdateDataAsync(giro, useTransaction);

                if (obj != null)
                {
                    obj.CopyFrom(serverData);
                    DbContext.CopySyncData(obj, giro);
                }
            }
        }

        #endregion

    }

}
