// ===================================================================================
// Author        : System
// Created date  : 08 Oct 2020 05:23:00
// Description   : mvCurrencyEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using AIO.IDOS3.Data.Entity;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Mobile.Data.Entity
{

    public class mvCurrencyEntityTypeConfig : IEntityTypeConfiguration<mvCurrency>, IEdmEntityConfiguration<mvCurrency>
    {

        #region Fields

        private vCurrencyEntityTypeConfig parentConfig = new vCurrencyEntityTypeConfig();

        #endregion

        #region Implements IEntityTypeConfiguration<mvCurrency>

        public void Configure(EntityTypeBuilder<mvCurrency> builder) { parentConfig.InternalConfigure(builder); }

        #endregion

        #region Implements IEdmEntityConfiguration<mvCurrency>

        public string EntitySetName { get { return parentConfig.EntitySetName; } }

        public void ConfigureEdmEntity(EntityTypeConfiguration<mvCurrency> builder) { parentConfig.InternalConfigureEdmEntity(builder); }

        #endregion

    }

}
