// ===================================================================================
// Author        : System
// Created date  : 02 Sep 2020 21:21:57
// Description   : mvWarehouseEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using AIO.IDOS3.Data.Entity;
using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Mobile.Data.Entity
{

    public class mvWarehouseEntityTypeConfig : IEntityTypeConfiguration<mvWarehouse>, IEdmEntityConfiguration<mvWarehouse>
    {

        #region Fields

        private vWarehouseEntityTypeConfig parentConfig = new vWarehouseEntityTypeConfig();

        #endregion

        #region Implements IEntityTypeConfiguration<mvWarehouse>

        public void Configure(EntityTypeBuilder<mvWarehouse> builder) { parentConfig.InternalConfigure(builder); }

        #endregion

        #region Implements IEdmEntityConfiguration<mvWarehouse>

        public string EntitySetName { get { return parentConfig.EntitySetName; } }

        public void ConfigureEdmEntity(EntityTypeConfiguration<mvWarehouse> builder) { parentConfig.InternalConfigureEdmEntity(builder); }

        #endregion

    }

}
