// ===================================================================================
// Author        : System
// Created date  : 09 Aug 2020 16:32:37
// Description   : mvDiscountGroupTableProvider partial class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Wismapi.Data;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Mobile.Data.Entity
{

    public partial class mvDiscountGroupTableProvider : DataTableProvider<mvDiscountGroup>
    {
        
        #region Methods

        protected override async Task OnEndInsertDataAsync(EndOperationDataEventArgs<mvDiscountGroup> e)
        {
            if (!e.IsError)
            {
                if (e.Data.ChildProducts != null)
                {
                    var childTableProvider = DbContext.GetDataTableProvider<mvDiscountGroupProductTableProvider>();

                    await InsertChilds(childTableProvider, e.Data.ID, e.Data.ChildProducts, e.UseTransaction);
                }                
            }

            await base.OnEndInsertDataAsync(e);
        }

        protected override async Task OnEndUpdateDataAsync(EndOperationDataEventArgs<mvDiscountGroup> e)
        {
            if (!e.IsError)
            {
                if (e.Data.ChildProducts != null)
                {
                    var childTableProvider = DbContext.GetDataTableProvider<mvDiscountGroupProductTableProvider>();

                    await DeleteChilds(childTableProvider, e.Data.ID, e.UseTransaction);
                    await InsertChilds(childTableProvider, e.Data.ID, e.Data.ChildProducts, e.UseTransaction);
                }
            }

            await base.OnEndUpdateDataAsync(e);
        }

        protected override async Task OnBeginDeleteDataAsync(BeginOperationDataEventArgs<mvDiscountGroup> e)
        {
            var childTableProvider = DbContext.GetDataTableProvider<mvDiscountGroupProductTableProvider>();

            await DeleteChilds(childTableProvider, e.Data.ID, e.UseTransaction);

            await base.OnBeginDeleteDataAsync(e);
        }



        private async Task InsertChilds(mvDiscountGroupProductTableProvider childTableProvider, int discountGroupID, ICollection<mvDiscountGroupProduct> childs, bool useTransaction)
        {
            foreach (var child in childs)
            {
                child.DiscountGroupID = discountGroupID;
                await childTableProvider.InsertDataAsync(child, useTransaction);
            }                
        }

        private async Task DeleteChilds(mvDiscountGroupProductTableProvider childTableProvider, int discountGroupID, bool useTransaction)
        {
            var deleteChilds = childTableProvider.GetDataByDiscountGroupID(discountGroupID);
            foreach (var child in deleteChilds)                
                await childTableProvider.DeleteDataAsync(child, useTransaction);
        }

        #endregion

    }

}
