// ===================================================================================
// Author        : System
// Created date  : 06 Aug 2020 17:30:59
// Description   : MobileDeviceEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AIO.IDOS3.Data.Entity
{

    public class MobileDeviceEntityTypeConfig : IEntityTypeConfiguration<MobileDevice>
    {

        #region Implements IEntityTypeConfiguration<MobileDevice>
        
        public void Configure(EntityTypeBuilder<MobileDevice> builder) { InternalConfigure(builder); }

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : MobileDevice
        {
            builder.ToTable("MobileDevice");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.ID });
        }
        
        #endregion

    }

}
