// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:45:52
// Description   : vCollectionRoutePlanEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vCollectionRoutePlanEntityTypeConfig : IEntityTypeConfiguration<vCollectionRoutePlan>, IEdmEntityConfiguration<vCollectionRoutePlan>
    {

        #region Implements IEntityTypeConfiguration<vCollectionRoutePlan>
        
        public void Configure(EntityTypeBuilder<vCollectionRoutePlan> builder) { InternalConfigure(builder); }

        #endregion
        
        #region Implements IEdmEntityConfiguration<vCollectionRoutePlan>

        public string EntitySetName { get; } = "vCollectionRoutePlans";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vCollectionRoutePlan> builder) { InternalConfigureEdmEntity(builder); }

        #endregion
        
        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vCollectionRoutePlan
        {
            builder.ToTable("vCollectionRoutePlan");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.ReferenceID, p.IsReferenceCustomerID });
        }
        
        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vCollectionRoutePlan
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.ReferenceID, p.IsReferenceCustomerID });
        }

        #endregion

    }

}
