// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:46:40
// Description   : vUserSiteEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vUserSiteEntityTypeConfig : IEntityTypeConfiguration<vUserSite>, IEdmEntityConfiguration<vUserSite>
    {

        #region Implements IEntityTypeConfiguration<vUserSite>
        
        public void Configure(EntityTypeBuilder<vUserSite> builder) { InternalConfigure(builder); }

        #endregion
        
        #region Implements IEdmEntityConfiguration<vUserSite>

        public string EntitySetName { get; } = "vUserSites";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vUserSite> builder) { InternalConfigureEdmEntity(builder); }

        #endregion
        
        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vUserSite
        {
            builder.ToTable("vUserSite");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.SiteID, p.UserID });
        }
        
        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vUserSite
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.SiteID, p.UserID });
        }

        #endregion

    }

}
