// ===================================================================================
// Author        : System
// Created date  : 30 Aug 2020 07:11:01
// Description   : mvCollectionRoutePlanSyncProvider partial class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Mobile.Data.Entity
{

    public partial class mvCollectionRoutePlanSyncProvider : DataSyncProvider<mvCollectionRoutePlan>
    {

        #region Properties
        
        public static string Selector = "ReferenceID,IsReferenceCustomerID,ReferenceCode,ReferenceName,Reference,CollectorID,IsCollectedByHeadOffice,CollectedBySiteID,CollectedByCompanyID,CollectedByAreaID,CollectedByRegionID,CollectedByTerritoryID,ReferenceBillContactPerson,ReferenceBillAddress1,ReferenceBillAddress2,ReferenceBillAddress3,ReferenceBillAddress,ReferenceBillCityID,ReferenceBillCity,ReferenceBillStateProvinceID,ReferenceBillStateProvince,ReferenceBillCountryID,ReferenceBillCountryName,ReferenceBillZipCode,ReferenceBillPhone1,ReferenceBillPhone2,ReferenceBillPhone3,ReferenceBillFax,ReferenceBillEmail,ReferenceBillLongitude,ReferenceBillLatitude,Week1,Week2,Week3,Week4,Day1,Day2,Day3,Day4,Day5,Day6,Day7,CreatedDate,ModifiedDate";

        #endregion

        #region Methods

        private async Task<Expression<Func<mvCollectionRoutePlan, bool>>> GetFilter()
        {
            var collectorIDs = await DbContext.GetDataTableProvider<mvCollectorTableProvider>().GetData().Select(p => p.ID).ToListAsync();

            Expression filter = null;
            var type = typeof(mvCollectionRoutePlan);
            var param = Expression.Parameter(type, "param");

            var propCollectorID = Expression.Property(param, "CollectorID");
            foreach (var id in collectorIDs)
            {
                var expr = Expression.MakeBinary(ExpressionType.Equal, propCollectorID, Expression.Constant(id, type.GetProperty("CollectorID").PropertyType));
                filter = (filter == null) ? expr : Expression.MakeBinary(ExpressionType.Or, filter, expr);
            }

            return Expression.Lambda<Func<mvCollectionRoutePlan, bool>>(filter, param);
        }



        protected override Exception OnDownloadAllData(bool continueOnError) { return OnDownloadAllDataAsync(continueOnError).Result; }
        protected override Exception OnUploadAllData(bool continueOnError) { return OnUploadAllDataAsync(continueOnError).Result; }
        protected override Exception OnDownloadData(mvCollectionRoutePlan obj, bool useTransaction) { return OnDownloadDataAsync(obj, useTransaction).Result; }
        protected override Exception OnUploadData(mvCollectionRoutePlan obj, bool useTransaction) { return OnUploadDataAsync(obj, useTransaction).Result; }


        protected override async Task<Exception> OnDownloadAllDataAsync(bool continueOnError)
        {
            Exception exception = null;

            var collectionRoutePlanTableProvider = DbContext.GetDataTableProvider<mvCollectionRoutePlanTableProvider>();
            var collectionRoutePlanServiceProvider = DataServiceContext.GetDataServiceProvider<mvCollectionRoutePlanServiceProvider>();

            DateTime? syncDate = null;

            List<mvCollectionRoutePlan> serverDataList = null;

            var minSyncDate = (DateTimeOffset?)await collectionRoutePlanTableProvider.GetData().MinAsync(p => p.SyncDate);

            for (int i = 0; i < DbContext.SyncMaxAttempts; i++)
            {
                try
                {
                    if (!syncDate.HasValue) syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();

                    var query = collectionRoutePlanServiceProvider.GetData().AddQueryOption("$select", Selector).Where(await GetFilter());

                    if (minSyncDate.HasValue)
                        query = query.Where(p => (p.CreatedDate > minSyncDate.Value) || ((p.ModifiedDate != null) && (p.ModifiedDate.Value > minSyncDate.Value)));

                    serverDataList = query.ToList();
                    break;
                }
                catch (Exception ex)
                {
                    if (i == (DbContext.SyncMaxAttempts - 1)) exception = ex;
                    else await Task.Delay(DbContext.SyncAttemptDelay);
                }
            }

            if (serverDataList != null)
            {
                int index = 0;
                foreach (var serverData in serverDataList)
                {
                    try
                    {
                        await ProcessLocalData(syncDate, 1, 1, serverData, null, collectionRoutePlanTableProvider, true);
                    }
                    catch (Exception ex)
                    {
                        if (!continueOnError)
                        {
                            exception = ex;
                            break;
                        }
                    }

                    index++;
                }
            }

            return exception;
        }
        
        protected override async Task<Exception> OnUploadAllDataAsync(bool continueOnError)
        {
            Exception exception = new NotImplementedException();

            return await Task.FromResult(exception);
        }


        protected override async Task<Exception> OnDownloadDataAsync(mvCollectionRoutePlan obj, bool useTransaction)
        {
            Exception exception = null;

            var collectionRoutePlanTableProvider = DbContext.GetDataTableProvider<mvCollectionRoutePlanTableProvider>();
            var collectionRoutePlanServiceProvider = DataServiceContext.GetDataServiceProvider<mvCollectionRoutePlanServiceProvider>();

            DateTime? syncDate = null;
            int status = 1;
            int attempts = 0;

            mvCollectionRoutePlan serverData = null;

            for (int i = 0; i < DbContext.SyncMaxAttempts; i++)
            {
                try
                {
                    if (!syncDate.HasValue) syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();

                    serverData = collectionRoutePlanServiceProvider.GetData().AddQueryOption("$select", Selector)
                        .Where(p => p.ReferenceID.Equals(serverData.ReferenceID) && p.IsReferenceCustomerID.Equals(serverData.IsReferenceCustomerID)).SingleOrDefault();
                    break;
                }
                catch (Exception ex)
                {
                    if (i == (DbContext.SyncMaxAttempts - 1)) { exception = ex; status = 0; }
                    else await Task.Delay(DbContext.SyncAttemptDelay);
                }
            }

            await ProcessLocalData(syncDate, status, attempts, serverData, obj, collectionRoutePlanTableProvider, useTransaction);

            return exception;
        }

        protected override async Task<Exception> OnUploadDataAsync(mvCollectionRoutePlan obj, bool useTransaction)
        {
            Exception exception = new NotImplementedException();

            return await Task.FromResult(exception);
        }



        private async Task ProcessLocalData(DateTime? syncDate, int status, int attempts, mvCollectionRoutePlan serverData, mvCollectionRoutePlan obj,
            mvCollectionRoutePlanTableProvider tableProvider, bool useTransaction)
        {
            var localDate = (syncDate.HasValue) ? syncDate.Value : await DbContext.GetDatabaseUtcDateTimeAsync();
            mvCollectionRoutePlan collectionRoutePlan = null;

            if (serverData == null)
            {
                collectionRoutePlan = new mvCollectionRoutePlan();
                collectionRoutePlan.ReferenceID = obj.ReferenceID;
                collectionRoutePlan.IsReferenceCustomerID = obj.IsReferenceCustomerID;

                await tableProvider.DeleteDataAsync(collectionRoutePlan, useTransaction);
            }
            else
            {
                var isInsert = false;
                collectionRoutePlan = await tableProvider.GetDataAsync(serverData.ReferenceID, serverData.IsReferenceCustomerID);
                if (collectionRoutePlan == null)
                {
                    isInsert = true;
                    collectionRoutePlan = new mvCollectionRoutePlan();
                }                

                collectionRoutePlan.CopyFrom(serverData);
                DbContext.SetSyncData(collectionRoutePlan, syncDate, localDate, status, attempts);

                if (isInsert)
                    await tableProvider.InsertDataAsync(collectionRoutePlan, useTransaction);
                else
                    await tableProvider.UpdateDataAsync(collectionRoutePlan, useTransaction);

                if (obj != null)
                {
                    obj.CopyFrom(serverData);
                    DbContext.CopySyncData(obj, collectionRoutePlan);
                }
            }
        }

        #endregion

    }

}
