// ===================================================================================
// Author        : System
// Created date  : 06 Aug 2020 17:31:14
// Description   : DiscountStrataEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AIO.IDOS3.Data.Entity
{

    public class DiscountStrataEntityTypeConfig : IEntityTypeConfiguration<DiscountStrata>
    {

        #region Implements IEntityTypeConfiguration<DiscountStrata>
        
        public void Configure(EntityTypeBuilder<DiscountStrata> builder) { InternalConfigure(builder); }

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : DiscountStrata
        {
            builder.ToTable("DiscountStrata");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.ID });
            builder.Property(p => p.ID).ValueGeneratedOnAdd();
        }
        
        #endregion

    }

}
