// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:45:58
// Description   : vDepositAccountTransactionEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vDepositAccountTransactionEntityTypeConfig : IEntityTypeConfiguration<vDepositAccountTransaction>, IEdmEntityConfiguration<vDepositAccountTransaction>
    {

        #region Implements IEntityTypeConfiguration<vDepositAccountTransaction>
        
        public void Configure(EntityTypeBuilder<vDepositAccountTransaction> builder) { InternalConfigure(builder); }

        #endregion
        
        #region Implements IEdmEntityConfiguration<vDepositAccountTransaction>

        public string EntitySetName { get; } = "vDepositAccountTransactions";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vDepositAccountTransaction> builder) { InternalConfigureEdmEntity(builder); }

        #endregion
        
        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vDepositAccountTransaction
        {
            builder.ToTable("vDepositAccountTransaction");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.AccountID, p.TransactionDateID });
        }
        
        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vDepositAccountTransaction
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.AccountID, p.TransactionDateID });
        }

        #endregion

    }

}
