// ===================================================================================
// Author        : System
// Created date  : 15 Sep 2020 03:26:59
// Description   : mvDiscountStrataEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using AIO.IDOS3.Data.Entity;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Mobile.Data.Entity
{

    public class mvDiscountStrataEntityTypeConfig : IEntityTypeConfiguration<mvDiscountStrata>, IEdmEntityConfiguration<mvDiscountStrata>
    {

        #region Fields

        private vDiscountStrataEntityTypeConfig parentConfig = new vDiscountStrataEntityTypeConfig();

        #endregion

        #region Implements IEntityTypeConfiguration<mvDiscountStrata>

        public void Configure(EntityTypeBuilder<mvDiscountStrata> builder)
        {
            parentConfig.InternalConfigure(builder);

            builder.HasOne(p => p.ExtendDiscountGroupProduct1)
                .WithOne(q => q.ExtendDiscountStrata1)
                .HasForeignKey<mvDiscountGroupProduct>(q => q.DiscountStrata1ID);

            builder.HasOne(p => p.ExtendDiscountGroupProduct2)
                .WithOne(q => q.ExtendDiscountStrata2)
                .HasForeignKey<mvDiscountGroupProduct>(q => q.DiscountStrata2ID);

            builder.HasOne(p => p.ExtendDiscountGroupProduct3)
                .WithOne(q => q.ExtendDiscountStrata3)
                .HasForeignKey<mvDiscountGroupProduct>(q => q.DiscountStrata3ID);

            builder.HasOne(p => p.ExtendDiscountGroupProduct4)
                .WithOne(q => q.ExtendDiscountStrata4)
                .HasForeignKey<mvDiscountGroupProduct>(q => q.DiscountStrata4ID);

            builder.HasOne(p => p.ExtendDiscountGroupProduct5)
                .WithOne(q => q.ExtendDiscountStrata5)
                .HasForeignKey<mvDiscountGroupProduct>(q => q.DiscountStrata5ID);

            builder.HasOne(p => p.ExtendSpecialDiscountGroupProduct1)
                .WithOne(q => q.ExtendSpecialDiscountStrata1)
                .HasForeignKey<mvDiscountGroupProduct>(q => q.SpecialDiscountStrata1ID);

            builder.HasOne(p => p.ExtendSpecialDiscountGroupProduct2)
                .WithOne(q => q.ExtendSpecialDiscountStrata2)
                .HasForeignKey<mvDiscountGroupProduct>(q => q.SpecialDiscountStrata2ID);

            builder.HasOne(p => p.ExtendSpecialDiscountGroupProduct3)
                .WithOne(q => q.ExtendSpecialDiscountStrata3)
                .HasForeignKey<mvDiscountGroupProduct>(q => q.SpecialDiscountStrata3ID);

            builder.HasOne(p => p.ExtendSpecialDiscountGroupProduct4)
                .WithOne(q => q.ExtendSpecialDiscountStrata4)
                .HasForeignKey<mvDiscountGroupProduct>(q => q.SpecialDiscountStrata4ID);

            builder.HasOne(p => p.ExtendSpecialDiscountGroupProduct5)
                .WithOne(q => q.ExtendSpecialDiscountStrata5)
                .HasForeignKey<mvDiscountGroupProduct>(q => q.SpecialDiscountStrata5ID);
        }

        #endregion

        #region Implements IEdmEntityConfiguration<mvDiscountStrata>

        public string EntitySetName { get { return parentConfig.EntitySetName; } }

        public void ConfigureEdmEntity(EntityTypeConfiguration<mvDiscountStrata> builder) { parentConfig.InternalConfigureEdmEntity(builder); }

        #endregion

    }

}
