// ===================================================================================
// Author        : System
// Created date  : 15 Sep 2020 03:26:59
// Description   : mvDiscountStrataSyncProvider partial class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Mobile.Data.Entity
{

    public partial class mvDiscountStrataSyncProvider : DataSyncProvider<mvDiscountStrata>
    {

        #region Properties
        
        public static string Selector = "ID,Code,Name,DiscountStrata,ValidDateFrom,ValidDateTo,StatusID,StatusName,CreatedDate,ModifiedDate";

        #endregion

        #region Methods

        private async Task<Expression<Func<mvDiscountStrata, bool>>> GetFilter()
        {
            var discountGroupProductTableProvider = DbContext.GetDataTableProvider<mvDiscountGroupProductTableProvider>();

            var discountStrata1IDs = await discountGroupProductTableProvider.GetData().Select(p => p.DiscountStrata1ID).Distinct().ToListAsync();
            var discountStrata2IDs = await discountGroupProductTableProvider.GetData().Select(p => p.DiscountStrata2ID).Distinct().ToListAsync();
            var discountStrata3IDs = await discountGroupProductTableProvider.GetData().Select(p => p.DiscountStrata3ID).Distinct().ToListAsync();
            var discountStrata4IDs = await discountGroupProductTableProvider.GetData().Select(p => p.DiscountStrata4ID).Distinct().ToListAsync();
            var discountStrata5IDs = await discountGroupProductTableProvider.GetData().Select(p => p.DiscountStrata5ID).Distinct().ToListAsync();

            var discountStrataIDs = new List<int?>();
            discountStrataIDs.AddRange(discountStrata1IDs);
            discountStrataIDs.AddRange(discountStrata2IDs);
            discountStrataIDs.AddRange(discountStrata3IDs);
            discountStrataIDs.AddRange(discountStrata4IDs);
            discountStrataIDs.AddRange(discountStrata5IDs);

            discountStrataIDs = discountStrataIDs.Distinct().ToList();

            Expression filter = null;
            var type = typeof(mvDiscountStrata);
            var param = Expression.Parameter(type, "param");

            var propID = Expression.Property(param, "ID");
            foreach (var id in discountStrataIDs)
            {
                if (!id.HasValue) continue;

                var expr = Expression.MakeBinary(ExpressionType.Equal, propID, Expression.Constant(id, type.GetProperty("ID").PropertyType));
                filter = (filter == null) ? expr : Expression.MakeBinary(ExpressionType.Or, filter, expr);
            }

            return Expression.Lambda<Func<mvDiscountStrata, bool>>(filter, param);
        }



        protected override Exception OnDownloadAllData(bool continueOnError) { return OnDownloadAllDataAsync(continueOnError).Result; }
        protected override Exception OnUploadAllData(bool continueOnError) { return OnUploadAllDataAsync(continueOnError).Result; }
        protected override Exception OnDownloadData(mvDiscountStrata obj, bool useTransaction) { return OnDownloadDataAsync(obj, useTransaction).Result; }
        protected override Exception OnUploadData(mvDiscountStrata obj, bool useTransaction) { return OnUploadDataAsync(obj, useTransaction).Result; }


        protected override async Task<Exception> OnDownloadAllDataAsync(bool continueOnError)
        {
            Exception exception = null;

            var discountStrataTableProvider = DbContext.GetDataTableProvider<mvDiscountStrataTableProvider>();
            var discountStrataServiceProvider = DataServiceContext.GetDataServiceProvider<mvDiscountStrataServiceProvider>();

            DateTime? syncDate = null;

            List<mvDiscountStrata> serverDataList = null;

            var minSyncDate = (DateTimeOffset?)await discountStrataTableProvider.GetData().MinAsync(p => p.SyncDate);

            for (int i = 0; i < DbContext.SyncMaxAttempts; i++)
            {
                try
                {
                    if (!syncDate.HasValue) syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();

                    var query = discountStrataServiceProvider.GetData().AddQueryOption("$select", Selector).Where(await GetFilter());

                    if (minSyncDate.HasValue)
                        query = query.Where(p => (p.CreatedDate > minSyncDate.Value) || ((p.ModifiedDate != null) && (p.ModifiedDate.Value > minSyncDate.Value)));
                        
                    serverDataList = query.ToList();
                    break;
                }
                catch (Exception ex)
                {
                    if (i == (DbContext.SyncMaxAttempts - 1)) exception = ex;
                    else await Task.Delay(DbContext.SyncAttemptDelay);
                }
            }

            if (serverDataList != null)
            {
                int index = 0;
                foreach (var serverData in serverDataList)
                {
                    try
                    {
                        await ProcessLocalData(syncDate, 1, 1, serverData, null, discountStrataTableProvider, true);
                    }
                    catch (Exception ex)
                    {
                        if (!continueOnError)
                        {
                            exception = ex;
                            break;
                        }
                    }

                    index++;
                }
                
                await DbContext.UpdateAllSyncDateAsync<mvDiscountStrata>(syncDate.Value);
            }

            return exception;
        }
        
        protected override async Task<Exception> OnUploadAllDataAsync(bool continueOnError)
        {
            Exception exception = new NotImplementedException();

            return await Task.FromResult(exception);
        }


        protected override async Task<Exception> OnDownloadDataAsync(mvDiscountStrata obj, bool useTransaction)
        {
            Exception exception = null;

            var discountStrataTableProvider = DbContext.GetDataTableProvider<mvDiscountStrataTableProvider>();
            var discountStrataServiceProvider = DataServiceContext.GetDataServiceProvider<mvDiscountStrataServiceProvider>();

            DateTime? syncDate = null;
            int status = 1;
            int attempts = 0;

            mvDiscountStrata serverData = null;

            for (int i = 0; i < DbContext.SyncMaxAttempts; i++)
            {
                try
                {
                    if (!syncDate.HasValue) syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();

                    serverData = discountStrataServiceProvider.GetData().AddQueryOption("$select", Selector)
                        .Where(p => (p.Code.ToLower() == obj.Code.ToLower())).SingleOrDefault();
                    break;
                }
                catch (Exception ex)
                {
                    if (i == (DbContext.SyncMaxAttempts - 1)) { exception = ex; status = 0; }
                    else await Task.Delay(DbContext.SyncAttemptDelay);
                }
            }

            await ProcessLocalData(syncDate, status, attempts, serverData, obj, discountStrataTableProvider, useTransaction);

            return exception;
        }

        protected override async Task<Exception> OnUploadDataAsync(mvDiscountStrata obj, bool useTransaction)
        {
            Exception exception = new NotImplementedException();

            return await Task.FromResult(exception);
        }



        private async Task ProcessLocalData(DateTime? syncDate, int status, int attempts, mvDiscountStrata serverData, mvDiscountStrata obj,
            mvDiscountStrataTableProvider tableProvider, bool useTransaction)
        {
            var localDate = (syncDate.HasValue) ? syncDate.Value : await DbContext.GetDatabaseUtcDateTimeAsync();
            mvDiscountStrata discountStrata = null;

            if (serverData == null)
            {
                discountStrata = new mvDiscountStrata();
                discountStrata.ID = obj.ID;

                await tableProvider.DeleteDataAsync(discountStrata, useTransaction);
            }
            else
            {
                var isInsert = false;
                var isDelete = false;
                discountStrata = await tableProvider.GetDataAsync(serverData.ID);
                if (discountStrata == null)
                {
                    isInsert = true;
                    discountStrata = new mvDiscountStrata();
                }                
                else if (discountStrata.IsDeleted)
                    isDelete = true;                    

                discountStrata.CopyFrom(serverData);
                DbContext.SetSyncData(discountStrata, syncDate, localDate, status, attempts);

                if (isInsert)
                    await tableProvider.InsertDataAsync(discountStrata, useTransaction);
                else if (isDelete)
                    await tableProvider.DeleteDataAsync(discountStrata, useTransaction);
                else
                    await tableProvider.UpdateDataAsync(discountStrata, useTransaction);

                if (obj != null)
                {
                    obj.CopyFrom(serverData);
                    DbContext.CopySyncData(obj, discountStrata);
                }
            }
        }

        #endregion

    }

}
