// ===================================================================================
// Author        : System
// Created date  : 30 Aug 2020 07:11:04
// Description   : mvProductLot class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using AIO.IDOS3.Data.Entity;

namespace AIO.IDOS3.Mobile.Data.Entity
{

    public partial class mvProductLot : vProductLot, ImvProductLot
    {

        #region Properties
                
        public new mvStockOnHandCurrent ExtendStockOnHandCurrent { get; set; }

        #endregion

    }

}
