// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:46:06
// Description   : vPaymentCollectionPopupEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vPaymentCollectionPopupEntityTypeConfig : IEntityTypeConfiguration<vPaymentCollectionPopup>, IEdmEntityConfiguration<vPaymentCollectionPopup>
    {

        #region Implements IEntityTypeConfiguration<vPaymentCollectionPopup>
        
        public void Configure(EntityTypeBuilder<vPaymentCollectionPopup> builder) { InternalConfigure(builder); }

        #endregion
        
        #region Implements IEdmEntityConfiguration<vPaymentCollectionPopup>

        public string EntitySetName { get; } = "vPaymentCollectionPopups";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vPaymentCollectionPopup> builder) { InternalConfigureEdmEntity(builder); }

        #endregion
        
        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vPaymentCollectionPopup
        {
            builder.ToTable("vPaymentCollectionPopup");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.DocumentID });
        }
        
        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vPaymentCollectionPopup
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.DocumentID });
        }

        #endregion

    }

}
