// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:46:34
// Description   : vStockReturnForDisposalEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vStockReturnForDisposalEntityTypeConfig : IEntityTypeConfiguration<vStockReturnForDisposal>, IEdmEntityConfiguration<vStockReturnForDisposal>
    {

        #region Implements IEntityTypeConfiguration<vStockReturnForDisposal>
        
        public void Configure(EntityTypeBuilder<vStockReturnForDisposal> builder) { InternalConfigure(builder); }

        #endregion
        
        #region Implements IEdmEntityConfiguration<vStockReturnForDisposal>

        public string EntitySetName { get; } = "vStockReturnForDisposals";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vStockReturnForDisposal> builder) { InternalConfigureEdmEntity(builder); }

        #endregion
        
        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vStockReturnForDisposal
        {
            builder.ToTable("vStockReturnForDisposal");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.DocumentID });
        }
        
        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vStockReturnForDisposal
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.DocumentID });
        }

        #endregion

    }

}
