// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:45:17
// Description   : SiteAccountingEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AIO.IDOS3.Data.Entity
{

    public class SiteAccountingEntityTypeConfig : IEntityTypeConfiguration<SiteAccounting>
    {

        #region Implements IEntityTypeConfiguration<SiteAccounting>
        
        public void Configure(EntityTypeBuilder<SiteAccounting> builder) { InternalConfigure(builder); }

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : SiteAccounting
        {
            builder.ToTable("SiteAccounting");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.SiteID });
        }
        
        #endregion

    }

}
