// ===================================================================================
// Author        : System
// Created date  : 03 Sep 2020 02:32:37
// Description   : mvAuthorizationEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using AIO.IDOS3.Data.Entity;
using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Mobile.Data.Entity
{

    public class mvAuthorizationEntityTypeConfig : IEntityTypeConfiguration<mvAuthorization>, IEdmEntityConfiguration<mvAuthorization>
    {

        #region Fields

        private vAuthorizationEntityTypeConfig parentConfig = new vAuthorizationEntityTypeConfig();

        #endregion

        #region Implements IEntityTypeConfiguration<mvAuthorization>

        public void Configure(EntityTypeBuilder<mvAuthorization> builder) { parentConfig.InternalConfigure(builder); }

        #endregion

        #region Implements IEdmEntityConfiguration<mvAuthorization>

        public string EntitySetName { get { return parentConfig.EntitySetName; } }

        public void ConfigureEdmEntity(EntityTypeConfiguration<mvAuthorization> builder) { parentConfig.InternalConfigureEdmEntity(builder); }

        #endregion

    }

}
