// ===================================================================================
// Author        : System
// Created date  : 03 Sep 2020 02:32:37
// Description   : mvAuthorizationSyncProvider partial class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Mobile.Data.Entity
{

    public partial class mvAuthorizationSyncProvider : DataSyncProvider<mvAuthorization>
    {

        #region Properties
        
        public static string Selector = "UserID,PermissionObjectID,UserName,PermissionObjectDescription,IsAuthorized";

        #endregion

        #region Methods

        private async Task<Expression<Func<mvAuthorization, bool>>> GetFilter()
        {
            var userID = await DbContext.GetDataTableProvider<mvUserTableProvider>().GetData().Select(p => p.ID).SingleAsync();

            Expression filter = null;
            var type = typeof(mvAuthorization);
            var param = Expression.Parameter(type, "param");

            var propUserID = Expression.Property(param, "UserID");
            filter = Expression.MakeBinary(ExpressionType.Equal, propUserID, Expression.Constant(userID, type.GetProperty("UserID").PropertyType));

            return Expression.Lambda<Func<mvAuthorization, bool>>(filter, param);
        }



        protected override Exception OnDownloadAllData(bool continueOnError) { return OnDownloadAllDataAsync(continueOnError).Result; }
        protected override Exception OnUploadAllData(bool continueOnError) { return OnUploadAllDataAsync(continueOnError).Result; }
        protected override Exception OnDownloadData(mvAuthorization obj, bool useTransaction) { return OnDownloadDataAsync(obj, useTransaction).Result; }
        protected override Exception OnUploadData(mvAuthorization obj, bool useTransaction) { return OnUploadDataAsync(obj, useTransaction).Result; }


        protected override async Task<Exception> OnDownloadAllDataAsync(bool continueOnError)
        {
            Exception exception = null;

            var authorizationTableProvider = DbContext.GetDataTableProvider<mvAuthorizationTableProvider>();
            var authorizationServiceProvider = DataServiceContext.GetDataServiceProvider<mvAuthorizationServiceProvider>();

            DateTime? syncDate = null;

            List<mvAuthorization> serverDataList = null;

            var minSyncDate = (DateTimeOffset?)await authorizationTableProvider.GetData().MinAsync(p => p.SyncDate);

            for (int i = 0; i < DbContext.SyncMaxAttempts; i++)
            {
                try
                {
                    if (!syncDate.HasValue) syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();

                    var query = authorizationServiceProvider.GetData().AddQueryOption("$select", Selector).Where(await GetFilter());

                    serverDataList = query.ToList();
                    break;
                }
                catch (Exception ex)
                {
                    if (i == (DbContext.SyncMaxAttempts - 1)) exception = ex;
                    else await Task.Delay(DbContext.SyncAttemptDelay);
                }
            }

            if (serverDataList != null)
            {
                int index = 0;
                foreach (var serverData in serverDataList)
                {
                    try
                    {
                        await ProcessLocalData(syncDate, 1, 1, serverData, null, authorizationTableProvider, true);
                    }
                    catch (Exception ex)
                    {
                        if (!continueOnError)
                        {
                            exception = ex;
                            break;
                        }
                    }

                    index++;
                }

                await DbContext.UpdateAllSyncDateAsync<mvAuthorization>(syncDate.Value);
            }

            return exception;
        }

        protected override async Task<Exception> OnUploadAllDataAsync(bool continueOnError)
        {
            Exception exception = new NotImplementedException();

            return await Task.FromResult(exception);
        }


        protected override async Task<Exception> OnDownloadDataAsync(mvAuthorization obj, bool useTransaction)
        {
            Exception exception = null;

            var authorizationTableProvider = DbContext.GetDataTableProvider<mvAuthorizationTableProvider>();
            var authorizationServiceProvider = DataServiceContext.GetDataServiceProvider<mvAuthorizationServiceProvider>();

            DateTime? syncDate = null;
            int status = 1;
            int attempts = 0;

            mvAuthorization serverData = null;

            for (int i = 0; i < DbContext.SyncMaxAttempts; i++)
            {
                try
                {
                    if (!syncDate.HasValue) syncDate = await DataServiceContext.GetDatabaseServerUtcDateTimeAsync();

                    serverData = authorizationServiceProvider.GetData().AddQueryOption("$select", Selector)
                        .Where(p => ((p.UserID == obj.UserID) && (p.PermissionObjectID == obj.PermissionObjectID))).SingleOrDefault();
                    break;
                }
                catch (Exception ex)
                {
                    if (i == (DbContext.SyncMaxAttempts - 1)) { exception = ex; status = 0; }
                    else await Task.Delay(DbContext.SyncAttemptDelay);
                }
            }

            await ProcessLocalData(syncDate, status, attempts, serverData, obj, authorizationTableProvider, useTransaction);

            return exception;
        }

        protected override async Task<Exception> OnUploadDataAsync(mvAuthorization obj, bool useTransaction)
        {
            Exception exception = new NotImplementedException();

            return await Task.FromResult(exception);
        }



        private async Task ProcessLocalData(DateTime? syncDate, int status, int attempts, mvAuthorization serverData, mvAuthorization obj,
            mvAuthorizationTableProvider tableProvider, bool useTransaction)
        {
            var localDate = (syncDate.HasValue) ? syncDate.Value : await DbContext.GetDatabaseUtcDateTimeAsync();
            mvAuthorization authorization = null;

            if (serverData == null)
            {
                authorization = new mvAuthorization();
                authorization.UserID = obj.UserID;
                authorization.PermissionObjectID = obj.PermissionObjectID;

                await tableProvider.DeleteDataAsync(authorization, useTransaction);
            }
            else
            {
                var isInsert = false;
                var isDelete = false;
                authorization = await tableProvider.GetDataAsync(serverData.UserID, serverData.PermissionObjectID);
                if (authorization == null)
                {
                    isInsert = true;
                    authorization = new mvAuthorization();
                }
                else
                    isDelete = true;

                authorization.CopyFrom(serverData);
                DbContext.SetSyncData(authorization, syncDate, localDate, status, attempts);

                if (isInsert)
                    await tableProvider.InsertDataAsync(authorization, useTransaction);
                else if (isDelete)
                    await tableProvider.DeleteDataAsync(authorization, useTransaction);
                else
                    await tableProvider.UpdateDataAsync(authorization, useTransaction);

                if (obj != null)
                {
                    obj.CopyFrom(serverData);
                    DbContext.CopySyncData(obj, authorization);
                }
            }
        }

        #endregion

    }

}
