// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:46:37
// Description   : vStockTransferSummaryEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vStockTransferSummaryEntityTypeConfig : IEntityTypeConfiguration<vStockTransferSummary>, IEdmEntityConfiguration<vStockTransferSummary>
    {

        #region Implements IEntityTypeConfiguration<vStockTransferSummary>

        public void Configure(EntityTypeBuilder<vStockTransferSummary> builder)
        {
            InternalConfigure(builder);

            builder.HasOne(p => p.Parent)
                .WithMany(q => q.ChildSummaries)
                .HasForeignKey(p => p.DocumentID)
                .OnDelete(DeleteBehavior.Cascade);
        }

        #endregion
        
        #region Implements IEdmEntityConfiguration<vStockTransferSummary>

        public string EntitySetName { get; } = "vStockTransferSummaries";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vStockTransferSummary> builder) { InternalConfigureEdmEntity(builder); }

        #endregion
        
        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vStockTransferSummary
        {
            builder.ToTable("vStockTransferSummary");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.DocumentID, p.ProductID });
        }
        
        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vStockTransferSummary
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.DocumentID, p.ProductID });
        }

        #endregion

    }

}
