// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:46:18
// Description   : vSFADashboardEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vSFADashboardEntityTypeConfig : IEntityTypeConfiguration<vSFADashboard>, IEdmEntityConfiguration<vSFADashboard>
    {

        #region Implements IEntityTypeConfiguration<vSFADashboard>
        
        public void Configure(EntityTypeBuilder<vSFADashboard> builder) { InternalConfigure(builder); }

        #endregion
        
        #region Implements IEdmEntityConfiguration<vSFADashboard>

        public string EntitySetName { get; } = "vSFADashboards";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vSFADashboard> builder) { InternalConfigureEdmEntity(builder); }

        #endregion
        
        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vSFADashboard
        {
            builder.ToTable("vSFADashboard");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.SiteID });
        }
        
        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vSFADashboard
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.SiteID });
        }

        #endregion

    }

}
