// ===================================================================================
// Author        : System
// Created date  : 15 Sep 2020 05:28:59
// Description   : mvDiscountGroupProductEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using AIO.IDOS3.Data.Entity;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Mobile.Data.Entity
{

    public class mvDiscountGroupProductEntityTypeConfig : IEntityTypeConfiguration<mvDiscountGroupProduct>, IEdmEntityConfiguration<mvDiscountGroupProduct>
    {

        #region Fields

        private vDiscountGroupProductEntityTypeConfig parentConfig = new vDiscountGroupProductEntityTypeConfig();

        #endregion

        #region Implements IEntityTypeConfiguration<mvDiscountGroupProduct>

        public void Configure(EntityTypeBuilder<mvDiscountGroupProduct> builder)
        {
            parentConfig.InternalConfigure(builder);

            builder.HasOne(p => p.Parent)
                .WithMany(q => q.ChildProducts)
                .HasForeignKey(p => p.DiscountGroupID)
                .OnDelete(DeleteBehavior.Cascade);
        }

        #endregion

        #region Implements IEdmEntityConfiguration<mvDiscountGroupProduct>

        public string EntitySetName { get { return parentConfig.EntitySetName; } }

        public void ConfigureEdmEntity(EntityTypeConfiguration<mvDiscountGroupProduct> builder) { parentConfig.InternalConfigureEdmEntity(builder); }

        #endregion

    }

}
