// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:46:24
// Description   : vStockItemStatusChangesDetailsEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vStockItemStatusChangesDetailsEntityTypeConfig : IEntityTypeConfiguration<vStockItemStatusChangesDetails>, IEdmEntityConfiguration<vStockItemStatusChangesDetails>
    {

        #region Implements IEntityTypeConfiguration<vStockItemStatusChangesDetails>
        
        public void Configure(EntityTypeBuilder<vStockItemStatusChangesDetails> builder) { InternalConfigure(builder); }

        #endregion
        
        #region Implements IEdmEntityConfiguration<vStockItemStatusChangesDetails>

        public string EntitySetName { get; } = "vStockItemStatusChangesDetails";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vStockItemStatusChangesDetails> builder) { InternalConfigureEdmEntity(builder); }

        #endregion
        
        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vStockItemStatusChangesDetails
        {
            builder.ToTable("vStockItemStatusChangesDetails");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.DocumentID, p.ProductID, p.ProductLotID });
        }
        
        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vStockItemStatusChangesDetails
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.DocumentID, p.ProductID, p.ProductLotID });
        }

        #endregion

    }

}
