// ===================================================================================
// Author        : System
// Created date  : 07 Aug 2020 02:46:03
// Description   : vInvoiceOpnameEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Data.Entity
{

    public class vInvoiceOpnameEntityTypeConfig : IEntityTypeConfiguration<vInvoiceOpname>, IEdmEntityConfiguration<vInvoiceOpname>
    {

        #region Implements IEntityTypeConfiguration<vInvoiceOpname>
        
        public void Configure(EntityTypeBuilder<vInvoiceOpname> builder) { InternalConfigure(builder); }

        #endregion
        
        #region Implements IEdmEntityConfiguration<vInvoiceOpname>

        public string EntitySetName { get; } = "vInvoiceOpnames";

        public void ConfigureEdmEntity(EntityTypeConfiguration<vInvoiceOpname> builder) { InternalConfigureEdmEntity(builder); }

        #endregion
        
        #region Methods

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : vInvoiceOpname
        {
            builder.ToTable("vInvoiceOpname");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.DocumentID });
        }
        
        public void InternalConfigureEdmEntity<TData>(EntityTypeConfiguration<TData> builder) where TData : vInvoiceOpname
        {
            // Define at least one key for EDM Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.DocumentID });
        }

        #endregion

    }

}
