// ===================================================================================
// Author        : System
// Created date  : 30 Aug 2020 07:11:04
// Description   : mvStockTransferSummaryEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using AIO.IDOS3.Data.Entity;
using Microsoft.AspNet.OData.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Wismapi.Data.Entity;

namespace AIO.IDOS3.Mobile.Data.Entity
{

    public class mvStockTransferSummaryEntityTypeConfig : IEntityTypeConfiguration<mvStockTransferSummary>, IEdmEntityConfiguration<mvStockTransferSummary>
    {

        #region Fields

        private vStockTransferSummaryEntityTypeConfig parentConfig = new vStockTransferSummaryEntityTypeConfig();

        #endregion

        #region Implements IEntityTypeConfiguration<mvStockTransferSummary>

        public void Configure(EntityTypeBuilder<mvStockTransferSummary> builder)
        {
            parentConfig.InternalConfigure(builder);

            builder.HasOne(p => p.Parent)
                .WithMany(q => q.ChildSummaries)
                .HasForeignKey(p => p.DocumentID)
                .OnDelete(DeleteBehavior.Cascade);
        }

        #endregion

        #region Implements IEdmEntityConfiguration<mvStockTransferSummary>

        public string EntitySetName { get { return parentConfig.EntitySetName; } }

        public void ConfigureEdmEntity(EntityTypeConfiguration<mvStockTransferSummary> builder) { parentConfig.InternalConfigureEdmEntity(builder); }

        #endregion

    }

}
