// ===================================================================================
// Author        : System
// Created date  : 06 Aug 2020 17:31:09
// Description   : CustomerBillGroupEntityTypeConfig class.
//
// Modified by   :
// Modified date :
// Comments      :
//
// NOTE: This file is initially generated by system and can be modified following
//       the requirement.
// ===================================================================================

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AIO.IDOS3.Data.Entity
{

    public class CustomerBillGroupEntityTypeConfig : IEntityTypeConfiguration<CustomerBillGroup>
    {

        #region Implements IEntityTypeConfiguration<CustomerBillGroup>
        
        public void Configure(EntityTypeBuilder<CustomerBillGroup> builder) { InternalConfigure(builder); }

        public void InternalConfigure<TData>(EntityTypeBuilder<TData> builder) where TData : CustomerBillGroup
        {
            builder.ToTable("CustomerBillGroup");

            // Define at least one key for Entity here. Example: builder.HasKey(p => new { p.ID });
            builder.HasKey(p => new { p.ID });
        }
        
        #endregion

    }

}
